In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import torch
import re
from sklearn.metrics import balanced_accuracy_score, roc_auc_score,accuracy_score,precision_recall_fscore_support
from Constants import *
from Preprocessing import *
from Models import *
import copy
from Utils import *
from DeepSurvivalModels import *
pd.set_option('display.max_rows', 200)

In [3]:
rad_data = DTDataset(use_smote=False)
control_data = DTDataset(radiomics_cluster_file=None,
                 radiomics_embedding_file=None)
rad_data.processed_df.T

/home/awentze2/git_repos/DigitalTwinVis/python/Preprocessing.py:186: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dummy_df = pd.get_dummies(df[to_onehot].fillna(0).astype(str),drop_first=False)
/home/awentze2/git_repos/DigitalTwinVis/python/Preprocessing.py:294: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  processed_df = preprocess_dt_data(df,self.ln_cols).fillna(0).drop(['DLT_Type'],axis=1)
/home/awentze2/git_repos/DigitalTwinVis/python/Preprocessing.py:186: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dummy_df = pd.get_dummies(df[to_onehot].fillna(0).astype(str),drop_first=False)
/home/awentze2/git_repos/DigitalTwinVis/python/Preprocessing.py:294: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  processed_df = preprocess_dt_data(df,self.ln_cols).fillna(0).drop(['DLT_Type'],axis=1)

id,3,5,6,7,8,9,10,11,13,14,...,10196,10197,10198,10199,10200,10201,10202,10203,10204,10205
hpv,1,0,1,1,1,1,-1,1,0,1,...,0,1,-1,0,1,1,0,1,0,1
age,55.969444,20.95,69.930556,72.319444,59.730556,60.083333,67.708333,57.858333,51.758333,56.25,...,47.619444,50.163889,70.888889,67.825,56.336111,49.566667,48.705556,77.116667,45.95,49.733333
packs_per_year,0.0,38.0,35.0,0.0,0.0,0.0,40.0,44.0,0.0,40.0,...,5.0,0.0,50.0,0.0,0.0,30.0,30.0,0.0,5.0,0.0
gender,1,1,0,1,1,1,1,1,1,1,...,0,1,0,1,1,1,1,1,1,1
Aspiration rate Pre-therapy,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
total_dose,66.0,72.0,70.0,70.0,66.0,66.0,69.96,70.0,70.0,70.0,...,70.0,72.0,66.0,70.0,69.96,70.0,72.0,70.0,69.96,69.96
dose_fraction,2.2,1.8,2.121212,2.121212,2.2,2.2,2.12,2.121212,2.0,2.121212,...,2.121212,1.8,2.2,2.121212,2.12,2.121212,1.714286,2.333333,2.12,2.12
OS (Calculated),6.033333,7.333333,7.466667,7.8,8.066667,8.733333,9.1,9.8,10.033333,10.033333,...,139.033333,139.3,140.6,142.833333,143.033333,143.2,144.366667,148.366667,152.6,155.533333
Locoregional control (Time),4.7,7.333333,7.466667,7.8,8.066667,8.733333,6.7,8.5,10.033333,10.033333,...,139.033333,139.3,140.6,142.833333,143.033333,143.2,144.366667,148.366667,152.6,155.533333
FDM (months),6.033333,7.333333,7.466667,7.8,8.066667,6.633333,9.1,9.8,10.033333,10.033333,...,139.033333,139.3,140.6,142.833333,143.033333,143.2,144.366667,136.033333,152.6,155.533333
time_to_event,4.7,6.0,6.0,6.0,8.066667,6.633333,6.0,8.5,6.0,10.033333,...,139.033333,139.3,140.6,142.833333,143.033333,143.2,6.0,136.033333,152.6,155.533333
"Overall Survival (1=alive, 0=dead)",0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
LRC,0,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
DC,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,0,1,1
bilateral,False,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
White/Caucasion,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
Hispanic/Latino,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
African American/Black,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Asian,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
cc_none,0,0,0,1,1,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
cc_platinum,0,1,1,0,0,0,0,0,1,0,...,1,1,0,1,1,1,0,0,1,1
cc_cetuximab,1,0,0,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
cc_others,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
no_dose_adjustment,1,1,1,1,1,1,1,1,1,1,...,1,0,1,1,1,1,1,1,1,1
dose_modified,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dose_delayed,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dose_cancelled,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dose_delayed_&_modified,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
regiment_modification,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
T-category_1,False,False,False,True,True,True,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False
T-category_2,True,False,False,False,False,False,False,True,False,True,...,True,False,False,True,False,False,False,False,False,False
T-category_3,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,True,True,False,False,True,False
T-category_4,False,True,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
N-category_0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
N-category_1,True,False,False,False,True,True,True,True,False,False,...,False,False,False,False,True,True,False,True,False,True
N-category_2,False,True,True,True,False,False,False,False,True,True,...,True,False,True,True,False,False,True,False,False,False
N-category_3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
AJCC_1,True,False,False,False,True,True,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
AJCC_2,False,False,False,True,False,False,False,False,False,True,...,False,False,False,False,True,True,False,False,False,False
AJCC_3,False,False,True,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,True
AJCC_4,False,True,False,False,False,False,False,False,True,False,...,True,False,True,True,False,False,True,False,True,False
Pathological Grade_0,True,False,False,True,False,False,False,False,False,False,...,True,False,False,True,False,False,False,True,False,False
Pathological Grade_1,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
Pathological Grade_2,False,True,True,False,False,False,True,True,True,False,...,False,True,False,False,True,False,False,False,False,True
Pathological Grade_3,False,False,False,False,True,True,False,False,False,True,...,False,False,False,False,False,True,True,False,True,False
Pathological Grade_4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
subsite_BOT,True,True,True,False,False,True,True,False,True,True,...,False,True,False,True,False,True,False,False,False,True
subsite_GPS,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
subsite_NOS,False,False,False,True,False,False,False,True,False,False,...,False,False,False,False,True,False,True,False,False,False
subsite_Soft palate,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
subsite_Tonsil,False,False,False,False,True,False,False,False,False,False,...,True,False,True,False,False,False,False,True,True,False
treatment_CC,True,True,True,False,False,True,True,True,True,True,...,True,False,False,True,True,True,True,False,True,True
treatment_IC+CC,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
treatment_IC+Radiation alone,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
treatment_Radiation alone,False,False,False,True,True,False,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False
DLT_Dermatological,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DLT_Neurological,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DLT_Gastrointestinal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DLT_Hematological,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DLT_Nephrological,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DLT_Vascular,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DLT_Infection (Pneumonia),0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DLT_Other,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DLT_Dermatological 2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DLT_Neurological 2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DLT_Gastrointestinal 2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
DLT_Hematological 2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DLT_Nephrological 2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DLT_Vascular 2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DLT_Infection (Pneumonia) 2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DLT_Other 2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CR Primary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PR Primary,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
SD Primary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CR Nodal,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
PR Nodal,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
SD Nodal,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CR Primary 2,0,1,0,1,1,0,0,0,0,1,...,1,1,0,1,1,1,0,1,1,1
PR Primary 2,1,0,1,0,0,1,0,1,1,0,...,0,0,1,0,0,0,1,0,0,0
SD Primary 2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CR Nodal 2,0,1,1,1,1,0,1,0,0,0,...,1,1,0,1,0,0,0,0,0,0
PR Nodal 2,1,0,0,0,0,1,0,1,1,1,...,0,0,1,0,1,1,1,1,1,1
SD Nodal 2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Decision 1 (Induction Chemo) Y/N,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
Decision 2 (CC / RT alone),1,1,1,0,0,1,1,1,1,1,...,1,1,0,1,1,1,1,0,1,1
Decision 3 Neck Dissection (Y/N),0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,1,1,0,1
Overall Survival (4 Years),0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
FT,0,1,1,1,0,0,1,0,1,0,...,0,0,0,0,0,0,1,0,0,0
Aspiration rate Post-therapy,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1A_ipsi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1A_contra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1B_ipsi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1B_contra,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2A_ipsi,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0
2A_contra,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2B_ipsi,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0
2B_contra,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3_ipsi,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
3_contra,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4_ipsi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4_contra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5A_ipsi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5A_contra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5B_ipsi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5B_contra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6_ipsi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6_contra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RPLN_ipsi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RPLN_contra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
rad_cluster_0,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,1,1,1,0
rad_cluster_1,0,1,0,0,0,1,0,0,1,1,...,0,0,1,0,0,1,0,0,0,1
rad_cluster_2,1,0,1,1,0,0,1,0,0,0,...,1,1,0,0,1,0,0,0,0,0
radiomics_embedding_0,0.012322,0.476228,-1.55529,-0.023764,-2.098841,-0.058749,-0.907719,0.039099,0.693724,0.214341,...,-1.351318,-1.153397,0.344122,-0.007692,-0.590558,1.205068,-0.514687,-2.24982,-1.215183,0.830576
radiomics_embedding_1,0.327461,-2.467426,1.542131,2.525694,-0.717295,1.538613,-0.118354,0.059295,0.765434,1.543772,...,0.477366,0.41707,0.371737,-0.059828,0.480753,0.468837,0.57072,-0.238424,-1.323805,-0.57551
radiomics_embedding_2,-0.73783,-1.350209,-0.85545,0.857898,0.855464,-0.640835,-0.191863,1.20148,0.805513,-0.899006,...,0.061171,0.358985,-0.529635,1.805527,0.273158,0.102134,0.378483,1.238406,1.562892,-0.723203
radiomics_embedding_3,-0.774294,2.316813,-0.183442,0.202643,-1.238519,1.446681,-1.029623,-0.045315,0.867933,0.885814,...,-0.435892,0.493711,1.394912,0.924935,-0.033577,0.472694,0.214891,0.188086,1.188759,0.300564
radiomics_embedding_4,1.064578,-1.50098,-0.768655,-1.909331,-0.197073,-0.225787,-1.783836,0.286066,0.954444,0.609762,...,-2.205945,-1.462108,0.239844,-2.204909,0.560368,0.346728,4.10318,0.060118,1.066953,0.322914

In [19]:
rad_model1,rad_model2,rad_model3,rad_smodel3 = load_transition_models('radcluster_')
rad_model1

BayesianOutcomeSimulator(
  (input_dropout): Dropout(p=0.1, inplace=False)
  (layers): ModuleList(
    (0): Linear(in_features=69, out_features=500, bias=True)
    (1): ReLU()
    (2): Linear(in_features=500, out_features=500, bias=True)
    (3): ReLU()
  )
  (batchnorm): BatchNorm1d(500, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (relu): Softplus(beta=1.0, threshold=20.0)
  (sigmoid): Sigmoid()
  (softmax): Softmax(dim=1)
  (disease_layer): Linear(in_features=501, out_features=3, bias=True)
  (nodal_disease_layer): Linear(in_features=501, out_features=3, bias=True)
  (dlt_layers): ModuleList(
    (0-4): 5 x Linear(in_features=501, out_features=1, bias=True)
  )
  (treatment_layer): Linear(in_features=501, out_features=6, bias=True)
)

In [20]:
control_model1,control_model2,control_model3,control_smodel3 = load_transition_models('control_')
control_model1

BayesianOutcomeSimulator(
  (input_dropout): Dropout(p=0.1, inplace=False)
  (layers): ModuleList(
    (0): Linear(in_features=61, out_features=500, bias=True)
    (1): ReLU()
    (2): Linear(in_features=500, out_features=500, bias=True)
    (3): ReLU()
  )
  (batchnorm): BatchNorm1d(500, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (relu): Softplus(beta=1.0, threshold=20.0)
  (sigmoid): Sigmoid()
  (softmax): Softmax(dim=1)
  (disease_layer): Linear(in_features=501, out_features=3, bias=True)
  (nodal_disease_layer): Linear(in_features=501, out_features=3, bias=True)
  (dlt_layers): ModuleList(
    (0-4): 5 x Linear(in_features=501, out_features=1, bias=True)
  )
  (treatment_layer): Linear(in_features=501, out_features=6, bias=True)
)

In [21]:
def temporal_loss(timestoevents,weights=None,maxtime=48,threshold=True):
    #list of expected times to events, usualy in order of Const.temporal_outcomes
    #basically longer = better, we count > maxtime (weeks) as no event
    if weights is None: 
        weights = [1 for i in range(len(timestoevents))]
    scores =  [(w*maxtime/t)for w,t in zip(weights,timestoevents)]
    if threshold:
        scores = [s*torch.lt(t,maxtime) for s,t in zip(scores,timestoevents)]
    scores = torch.stack(scores).sum(axis=0)
    return scores

def outcome_loss(ypred,weights=None):
    #default weights is bad
    if weights is None: 
        print('using default outcome loss weights, which is probably wrong since bad stuff should be negative')
        weights = [1 for i in range(ypred.shape[1])]
    l = torch.mul(ypred[:,0],weights[0])
    for i,weight in enumerate(weights[1:]):
        #weights with negative values will invert the outcome so e.g. Regional control becomes no regional control
        #so the penaly is correct
        newloss = torch.mul(ypred[:,i+1],weight)
        l = torch.add(l,newloss)
    return l

def calc_optimal_decisions(dataset,ids,m1,m2,m3,sm3,
                           weights=[0,0.5,.5,0], #weight for OS, FT, AS, and LRC as binary probabilities
                           tweights=[1,1,1,1], #weight for OS, LRC, FDM, and event (any + FT or AS at 6m) as time to event in weeks
                           outcome_loss_func=None,
                           threshold_temporal_loss = False,
                           maxtime=48,
                           get_transitions=True):
    m1.eval()
    m2.eval()
    m3.eval()
    sm3.eval()
    device = m1.get_device()
    data = dataset.processed_df.copy().loc[ids]
    
    def get_dlt(state):
        if state == 2:
            return data[Const.dlt2].copy()
        d = data[Const.dlt1].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_pd(state):
        if state == 2:
            return data[Const.primary_disease_states2].copy()
        d = data[Const.primary_disease_states].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_nd(state):
        if state == 2:
            return data[Const.nodal_disease_states2].copy()
        d = data[Const.nodal_disease_states].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_cc(state):
        res = data[Const.ccs].copy()
        if state == 1:
            res.values[:,:] = np.zeros(res.values.shape)
        return res
    
    def get_mod(state):
        res = data[Const.modifications].copy()
        #this should have an ic condition but we don't use it anumore anywa
        return res
        
    def formatdf(d):
        d = df_to_torch(d).to(device)
        return d
    
    
    outcomedf = data[Const.outcomes]
    baseline = dataset.get_state('baseline').loc[ids]
    baseline_input = formatdf(baseline)

        
    if outcome_loss_func is None:
        outcome_loss_func = outcome_loss
    
    cat = lambda x: torch.cat([xx.to(device) for xx in x],axis=1).to(device)
    format_transition = lambda x: x.to(device)
    def get_outcome(d1,d2,d3):
        d1 = torch.full((len(ids),1),d1).type(torch.FloatTensor)
        d2 = torch.full((len(ids),1),d2).type(torch.FloatTensor)
        d3 = torch.full((len(ids),1),d3).type(torch.FloatTensor)
        
        tinput1 = cat([baseline_input,d1])
        ytransition = m1(tinput1)
        [ypd1,ynd1,ymod,ydlt1] = [format_transition(xx) for xx in ytransition['predictions']]
        d1_thresh = torch.gt(d1,.5).view(-1,1).to(device)
        ypd1[:,0:2] = ypd1[:,0:2]*d1_thresh
        ynd1[:,0:2] = ynd1[:,0:2]*d1_thresh
        
        tinput2 = cat([baseline_input,ypd1,ynd1,ymod,ydlt1,d1,d2])
        ytransition2 = m2(tinput2)
        [ypd2,ynd2,ycc,ydlt2] = [format_transition(xx) for xx in ytransition2['predictions']]
        
        input3 = cat([baseline_input, ypd2, ynd2, ycc, ydlt2, d1, d2,d3])
        outcome = m3(input3)['predictions']
        temporal_outcomes = sm3.time_to_event(input3,n_samples=1)
        
        transitions = {
            'pd1': ypd1,
            'nd1': ynd1,
            'nd2': ynd2,
            'pd2': ypd2,
            'mod': ymod,
            'cc': ycc,
            'dlt1': ydlt1,
            'dlt2': ydlt2,
        }
        return outcome, temporal_outcomes, transitions

    losses = []
    loss_order = []
    transitions = {}
    for d1 in [0,1]:
        for d2 in [0,1]:
            for d3 in [0,1]:
                outcomes, tte, transition_entry = get_outcome(d1,d2,d3)
                loss = outcome_loss_func(outcomes,weights)
                tloss = temporal_loss(tte,tweights,maxtime=maxtime,threshold=threshold_temporal_loss)
                loss += tloss
                losses.append(loss)
                loss_order.append([d1,d2,d3])
                transitions[str(d1)+str(d2)+str(d3)] = transition_entry
    losses = torch.stack(losses,axis=1)
    optimal_decisions = [loss_order[i] for i in torch.argmin(losses,axis=1)]
    result = torch.tensor(optimal_decisions).type(torch.FloatTensor)
    print(result.sum(axis=0),result.shape[0])
    if get_transitions:
        opt_transitions = {k: torch.zeros(v.shape).type(torch.FloatTensor) for k,v in transitions['000'].items()}
        for i,od in enumerate(optimal_decisions):
            key = ''.join([str(o) for o in od])
            entry = transitions[key]
            for kk,vv in entry.items():
                opt_transitions[kk][i,:] = vv[i,:]
        return result, opt_transitions
    return result

test, testtest = get_tt_split()
calc_optimal_decisions(rad_data,
                       testtest,rad_model1,rad_model2,rad_model3,rad_smodel3,
                       threshold_temporal_loss=False,
                       maxtime=48,
                       weights=[0,0,0,0],
                       tweights=[2,0.1,0,0],
                      )

tensor([15.,  0.,  0.]) 147

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 {'pd1': tensor([[0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [5.9083e-01, 3.9223e-01, 1.6937e-02],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [7.6920e-01, 2.1679e-01, 1.4016e-02],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [4.2253e-01, 5.7747e-01, 2.6992e-20],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [6.1860e-01, 3.8140e-01, 3.0974e-20],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [8.6457e-01, 1.1976e-01, 1.5670e-02],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [5.8355e-01, 3.9607e-01, 2.0379e-02],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [4.8698e-01, 5.1302e-01, 2.5052e-20],
          [8.4743e-01, 1.3915e-01, 1.3421e-02],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [7.8108e-01, 2.0026e-01, 1.8657e-02],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [7.9358e-01, 1.9501e-01, 1.1418e-02],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [7.4266e-01, 2.4130e-01, 1.6044e-02],
          [1.1756e-01, 8.8150e-01, 9.4102e-04],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [6.7940e-01, 3.0021e-01, 2.0393e-02],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [1.5348e-01, 8.3760e-01, 8.9269e-03],
          [3.1927e-01, 6.7023e-01, 1.0498e-02],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01]], grad_fn=<CopySlices>),
  'nd1': tensor([[0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [3.9356e-03, 9.9221e-01, 3.8535e-03],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [5.0128e-03, 9.9013e-01, 4.8580e-03],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [7.6286e-33, 1.0000e+00, 7.6286e-33],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [1.1392e-32, 1.0000e+00, 1.1392e-32],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [9.4084e-03, 9.8135e-01, 9.2451e-03],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [6.7392e-03, 9.8675e-01, 6.5153e-03],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [8.4099e-33, 1.0000e+00, 8.4099e-33],
          [6.5411e-03, 9.8712e-01, 6.3415e-03],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [7.1310e-03, 9.8596e-01, 6.9052e-03],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [3.9681e-03, 9.9220e-01, 3.8299e-03],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [5.1708e-03, 9.8981e-01, 5.0232e-03],
          [7.4323e-05, 9.9985e-01, 7.3488e-05],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [8.0361e-03, 9.8423e-01, 7.7377e-03],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [2.7064e-03, 9.9459e-01, 2.7012e-03],
          [1.8698e-03, 9.9629e-01, 1.8443e-03],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01],
          [0.0000e+00, 0.0000e+00, 3.3333e-01]], grad_fn=<CopySlices>),
  'nd2': tensor([[0.8050, 0.1828, 0.0122],
          [0.8181, 0.1808, 0.0011],
          [0.6601, 0.3305, 0.0094],
          [0.6649, 0.3091, 0.0260],
          [0.5636, 0.3872, 0.0492],
          [0.4359, 0.5214, 0.0427],
          [0.4936, 0.4825, 0.0239],
          [0.4153, 0.5589, 0.0258],
          [0.5630, 0.4063, 0.0307],
          [0.4873, 0.4889, 0.0239],
          [0.3983, 0.5702, 0.0314],
          [0.6530, 0.3303, 0.0167],
          [0.4260, 0.5307, 0.0433],
          [0.4374, 0.5196, 0.0430],
          [0.5428, 0.4165, 0.0407],
          [0.5022, 0.4618, 0.0360],
          [0.7037, 0.2925, 0.0039],
          [0.5538, 0.4093, 0.0369],
          [0.3814, 0.5791, 0.0395],
          [0.5784, 0.3977, 0.0239],
          [0.6246, 0.3400, 0.0354],
          [0.4771, 0.4847, 0.0381],
          [0.5510, 0.4075, 0.0416],
          [0.5787, 0.4111, 0.0103],
          [0.3517, 0.6463, 0.0020],
          [0.5771, 0.3930, 0.0299],
          [0.5294, 0.4693, 0.0013],
          [0.6464, 0.3416, 0.0120],
          [0.4238, 0.5373, 0.0389],
          [0.4690, 0.5040, 0.0270],
          [0.4527, 0.4974, 0.0499],
          [0.5042, 0.4450, 0.0508],
          [0.4521, 0.5079, 0.0400],
          [0.5055, 0.4472, 0.0473],
          [0.6049, 0.3788, 0.0164],
          [0.8011, 0.1875, 0.0114],
          [0.4929, 0.4710, 0.0361],
          [0.5748, 0.3922, 0.0330],
          [0.4148, 0.5600, 0.0253],
          [0.4350, 0.5299, 0.0351],
          [0.5868, 0.3765, 0.0367],
          [0.7269, 0.2713, 0.0017],
          [0.6029, 0.3663, 0.0308],
          [0.6532, 0.3377, 0.0091],
          [0.4457, 0.5088, 0.0456],
          [0.6211, 0.3679, 0.0110],
          [0.6256, 0.3449, 0.0295],
          [0.5088, 0.4697, 0.0215],
          [0.5717, 0.3948, 0.0335],
          [0.4164, 0.5388, 0.0448],
          [0.7610, 0.2293, 0.0097],
          [0.6021, 0.3536, 0.0443],
          [0.6626, 0.3076, 0.0297],
          [0.4138, 0.5388, 0.0474],
          [0.4433, 0.5187, 0.0380],
          [0.5157, 0.4412, 0.0431],
          [0.6026, 0.3727, 0.0247],
          [0.4093, 0.5501, 0.0406],
          [0.8069, 0.1923, 0.0008],
          [0.4659, 0.4888, 0.0453],
          [0.4284, 0.5395, 0.0321],
          [0.5511, 0.4114, 0.0374],
          [0.4607, 0.5010, 0.0383],
          [0.4493, 0.5212, 0.0296],
          [0.4487, 0.5495, 0.0018],
          [0.4828, 0.4772, 0.0400],
          [0.4665, 0.4958, 0.0377],

In [32]:
def get_unique_sequence(array):
    #converts a row of boolean values to a unique number e.g. [1,1,0] => 11, [0,0,1] => 100
    uniqueify = lambda r: torch.sum(torch.stack([i*(10**ii) for ii,i in enumerate(r)]))
    return torch_apply_along_axis(uniqueify,array)

def train_decision_model_triplet(
    tmodel1,
    tmodel2,
    tmodel3,
    smodel3,
    dataset = None,
    use_default_split=True,
    use_bagging_split=False,
    use_attention=True,
    lr=.001,
    epochs=10000,
    patience=5,
    weights=[0,.5,.5,0], #realtive weight of survival, feeding tube, aspiration, andl lrc
    tweights=[1,1,1,0], #weight for OS, LRC, FDM, and event (any + FT or AS at 6m) as time to event in weeks
    opt_weights=[1,1,1], #weights for policy model for optimal decisions
    imitation_weights=[.5,1,1],#weights of imitation decisions, because ic overtrains too quickly
    imitation_weight=1,
    reward_weight=1,
    imitation_triplet_weight=2,
    reward_triplet_weight = 2,
    shufflecol_chance = 0.2,
    split=.7,
    resample_training=False,
    save_path='../data/models/',
    file_suffix='',
    verbose=True,
    use_gpu=False,
    **model_kwargs,
):
    tmodel1.eval()
    tmodel2.eval()
    tmodel3.eval()

    train_ids, test_ids = get_tt_split(use_default_split=use_default_split,use_bagging_split=use_bagging_split,resample_training=resample_training)
    true_ids = train_ids + test_ids #for saving memory without upsampling
    if dataset is None:
        dataset = DTDataset()
    data = dataset.processed_df.copy()
    
    def get_dlt(state):
        if state == 2:
            return data[Const.dlt2].copy()
        d = data[Const.dlt1].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_pd(state):
        if state == 2:
            return data[Const.primary_disease_states2].copy()
        d = data[Const.primary_disease_states].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_nd(state):
        if state == 2:
            return data[Const.nodal_disease_states2].copy()
        d = data[Const.nodal_disease_states].copy()
        if state < 1:
            d.values[:,:] = 0
        return d
    
    def get_cc(state):
        res = data[Const.ccs].copy()
        if state == 1:
            res.values[:,:] = np.zeros(res.values.shape)
        return res
    
    def get_mod(state):
        res = data[Const.modifications].copy()
        #this should have an ic condition but we don't use it anumore anywa
        return res
        
    outcomedf = data[Const.outcomes]
    baseline = dataset.get_state('baseline')
    
    def formatdf(d,dids=train_ids):
        d = df_to_torch(d.loc[dids]).to(model.get_device())
        return d
    
    def makegrad(v):
        if not v.requires_grad:
            v.requires_grad=True
        return v
    
    if use_attention:
        model = DecisionAttentionModel(baseline.shape[1],**model_kwargs)
    else:
        model_kwargs = {k:v for k,v in model_kwargs.items() if 'attention' not in k and 'embed' not in k}
        model = DecisionModel(baseline.shape[1],**model_kwargs)
        
    device = 'cpu'
    if use_gpu and torch.cuda.is_available():
        device = 'cuda'
        
    model.set_device(device)

    tmodel1.set_device(device)
    tmodel2.set_device(device)
    tmodel3.set_device(device)
    smodel3.set_device(device)
    hashcode = str(hash(','.join([str(i) for i in train_ids])))
    
    save_file = save_path + 'model_' + model.identifier +'_hash' + hashcode + file_suffix + '.tar'
    model.fit_normalizer(df_to_torch(baseline.loc[train_ids]))
    optimizer = torch.optim.Adam(model.parameters(),lr=lr)
    
    
    optimal_train,transitions_train = calc_optimal_decisions(dataset,train_ids,tmodel1,tmodel2,tmodel3,smodel3,
                                           weights=weights,tweights=tweights,
                                          )
    optimal_test,transitions_test = calc_optimal_decisions(dataset,test_ids,tmodel1,tmodel2,tmodel3,smodel3,
                                          weights=weights,tweights=tweights,
                                         )
    optimal_train = optimal_train.to(model.get_device())
    optimal_test = optimal_test.to(model.get_device())
    mse = torch.nn.MSELoss()
    bce = torch.nn.BCELoss()
    
    def compare_decisions(d1,d2,d3,ids):
#         ypred = np.concatenate([dd.cpu().detach().numpy().reshape(-1,1) for dd in [d1,d2,d3]],axis=1)
        ytrue = df_to_torch(outcomedf.loc[ids])
        dloss = bce(d1.view(-1),ytrue[:,0])
        dloss += bce(d2.view(-1),ytrue[:,1])
        dloss += bce(d3,view(-1),ytrue[:,2])
        return dloss
        
    def remove_decisions(df):
        cols = [c for c in df.columns if c not in Const.decisions ]
        ddf = df[cols]
        return ddf
    
    makeinput = lambda step,dids: df_to_torch(remove_decisions(dataset.get_input_state(step=step,ids=dids)))
    threshold = lambda x: torch.gt(x,torch.rand(x.shape[0])).type(torch.FloatTensor)

    randchoice = lambda x: x[torch.randint(len(x),(1,))[0]]
    tloss_func = torch.nn.TripletMarginLoss()
    def get_tloss(row,step,yt,x,imitation=True):
        if yt[:,step].std() < .001:
            return torch.tensor([0]).to(device)
        positive_idx= torch.nonzero(yt[:,step] == yt[row,step])
        if len(positive_idx) <= 1:
            print('no losses','n positive',len(positive_idx),'yt',yt[row,step],'row',row,'step',step,'imitation',imitation,end='\r')
            return torch.tensor([0]).to(device)
        positive_idx = torch.stack([ii for ii in positive_idx if ii != row]).view(-1)
        negative_idx = torch.tensor([ii for ii in range(x.shape[0]) if ii not in positive_idx and ii != row])
        if len(positive_idx) < 1 or len(negative_idx) < 1:
            print('no losses','n positive',len(positive_idx),'n negative',len(negative_idx),'yt',yt[row,step],'row',row,'step',step,'imitation',imitation,end='\r')
            return torch.tensor([0]).to(device)
        positive = x[randchoice(positive_idx)]
        negative = x[randchoice(negative_idx)]
        anchor = x[row]
        if use_attention:
            [anchor_embedding,pos_embedding,neg_embedding] = [model.get_embedding(xx.view(1,-1),position=step,use_saved_memory=True) for xx in [anchor,positive,negative]]
        else:    
            [anchor_embedding,pos_embedding,neg_embedding] = [model.get_embedding(xx.view(1,-1),position=step,concatenate=False)[int(imitation)] for xx in [anchor,positive,negative]]
        tloss = tloss_func(anchor_embedding,pos_embedding,neg_embedding)
        return tloss
    #save the inputs from the whole dataset for future reference
    if use_attention:
        full_data = []
        for mstep in [0,1,2]:
            full_data_step = [baseline, get_dlt(min(mstep,1)),
                         get_dlt(mstep),get_pd(mstep),get_nd(mstep),get_cc(mstep),get_mod(mstep)]
            full_data_step = torch.cat([formatdf(fd,true_ids) for fd in full_data_step],axis=1)
            full_data.append(full_data_step)
        full_data = torch.stack(full_data)
        model.save_memory(full_data)
        print(full_data.shape)
        
    def step(train=True):
        if train:
            model.train(True)
            tmodel1.train(True)
            tmodel2.train(True)
            tmodel3.train(True)
            optimizer.zero_grad()
            ids = train_ids
            y_opt = makegrad(optimal_train)
            transition_dict = {k: torch.clone(v).detach() for k,v in transitions_train.items()}
        else:
            ids = test_ids
            model.eval()
            tmodel1.eval()
            tmodel2.eval()
            tmodel3.eval()
            y_opt = makegrad(optimal_test)
            print(y_opt.mean(axis=0))
            transition_dict = {k: torch.clone(v).detach() for k,v in transitions_test.items()}
        model.set_device(device)
        ytrain = df_to_torch(outcomedf.loc[ids]).to(device)
        #imitation losses and decision 1
        xxtrained = [baseline, get_dlt(0),get_dlt(0),get_pd(0),get_nd(0),get_cc(0),get_mod(0)]
        xxtrain = [formatdf(xx,ids) for xx in xxtrained]
        xxtrain = torch.cat(xxtrain,axis=1).to(device)
        o1 = model(xxtrain,position=0,use_saved_memory= (not train))
        decision1_imitation = o1[:,3]
        decision1_opt = o1[:,0]
    
        imitation_loss1 = bce(decision1_imitation,ytrain[:,0])
        imitation_loss1 = torch.mul(imitation_loss1,imitation_weights[0])
        opt_loss1 = bce(decision1_opt,y_opt[:,0])
        opt_loss1 = torch.mul(opt_loss1,opt_weights[0])
        
        x1_imitation = [baseline, get_dlt(1),get_dlt(0),get_pd(1),get_nd(1),get_cc(1),get_mod(1)]
        x1_imitation = [formatdf(xx1,ids) for xx1 in x1_imitation]
        x1_imitation = torch.cat(x1_imitation,axis=1).to(device)
        
        o2 = model(x1_imitation,position=1,use_saved_memory= (not train))
            
        decision2_imitation = o2[:,4]
            
        imitation_loss2 =  bce(decision2_imitation,ytrain[:,1])
        imitation_loss2 = torch.mul(imitation_loss2,imitation_weights[1])
        
        
        x2_imitation = [baseline, get_dlt(1),get_dlt(2),get_pd(2),get_nd(2),get_cc(2),get_mod(2)]
        
        x2_imitation = [formatdf(xx2,ids) for xx2 in x2_imitation]
        x2_imitation = torch.cat(x2_imitation,axis=1).to(device)
        
        
        o3 = model(x2_imitation,position=2,use_saved_memory= (not train))
        
        decision3_imitation = o3[:,5]
        
        imitation_loss3 = bce(decision3_imitation,ytrain[:,2])
        imitation_loss3 = torch.mul(imitation_loss3,imitation_weights[2])
        
        opt_input2 = [
            formatdf(baseline,ids), 
            transition_dict['dlt1'],
            formatdf(get_dlt(0),ids),
            transition_dict['pd1'],
            transition_dict['nd1'], 
            formatdf(get_cc(0),ids),
            transition_dict['mod']
                 ]
        opt_input2 = [o.to(device) for o in opt_input2]

        opt_input2 = torch.cat(opt_input2,axis=1).to(device)
        decision2_opt = model(opt_input2,position=1,use_saved_memory= (not train))[:,1]
        
        opt_loss2 = bce(decision2_opt,y_opt[:,1])
        opt_loss2 = torch.mul(opt_loss2,opt_weights[1])
        
        opt_input3 = [
            formatdf(baseline,ids),
            transition_dict['dlt1'],
            transition_dict['dlt2'],
            transition_dict['pd2'],
            transition_dict['nd2'],
            transition_dict['cc'],
            transition_dict['mod'],
        ]
        opt_input3 = [o.to(device) for o in opt_input3]
        opt_input3 = torch.cat(opt_input3,axis=1).to(device)
        decision3_opt = model(opt_input3,position=2,use_saved_memory= (not train))[:,2]
        
        opt_loss3 = bce(decision3_opt,y_opt[:,2])
        opt_loss3 = torch.mul(opt_loss3,opt_weights[2])
        
        iloss = torch.add(torch.add(imitation_loss1,imitation_loss2),imitation_loss3)
        iloss = torch.mul(iloss,imitation_weight)
        
        reward_loss = torch.add(torch.add(opt_loss1,opt_loss2),opt_loss3)
        reward_loss =torch.mul(reward_loss,reward_weight)
        
        loss = torch.add(iloss,reward_loss)
        
        imitation_tloss = torch.FloatTensor([0]).to(device)
        opt_tloss = torch.FloatTensor([0]).to(device)
        n_rows = xxtrain.shape[0]
        if reward_triplet_weight + imitation_triplet_weight > 0.0001:
            for i in range(n_rows):
                
                if imitation_triplet_weight > .0001:
                    imitation_tloss += get_tloss(i,0,ytrain,xxtrain,True)
                    imitation_tloss += get_tloss(i,1,ytrain,x1_imitation,True)
                    imitation_tloss += get_tloss(i,2,ytrain,x2_imitation,True)
                if reward_triplet_weight > .0001:
                    opt_tloss += get_tloss(i,0,y_opt,xxtrain,False)
                    opt_tloss += get_tloss(i,1,y_opt,opt_input2,False)
                    opt_tloss += get_tloss(i,2,y_opt,opt_input3,False)
            loss += torch.mul(imitation_tloss[0],imitation_triplet_weight/n_rows)
            loss += torch.mul(opt_tloss[0],reward_triplet_weight/n_rows)
        losses = [iloss,reward_loss,imitation_tloss*imitation_triplet_weight/n_rows,opt_tloss*reward_triplet_weight/n_rows]
        
        if train:
            loss.backward()
            optimizer.step()
            return losses
        else:
            scores = []
            distributions = [decision1_opt.mean().item(),decision2_opt.mean().item(),decision3_opt.mean().item()]
            imitation = [decision1_imitation,decision2_imitation,decision3_imitation]
            optimal = [decision1_opt,decision2_opt,decision3_opt]
            for i,decision_im in enumerate(imitation):
                deci = decision_im.cpu().detach().numpy()
                deci0 = (deci > .5).astype(int)
                iout = ytrain[:,i].cpu().detach().numpy()
                acci = accuracy_score(iout,deci0)
                try:
                    auci = roc_auc_score(iout,deci)
                except:
                    auci = -1
                
                deco = optimal[i].cpu().detach().numpy()
                deci0 = (deco > .5).astype(int)
                oout = y_opt[:,i].cpu().detach().numpy()
                acco = accuracy_score(oout,deci0)
                try:
                    auco = roc_auc_score(oout,deco)
                except:
                    auco=-1
                scores.append({'decision': i,'optimal_auc': auco,'imitation_auc': auci,'optimal_acc': acco,'imitation_acc': acci})
            return losses, scores, distributions
        
    best_val_loss = torch.tensor(1000000000.0)
    steps_since_improvement = 0
    best_val_score = {}
    
    for epoch in range(epochs):
        losses = step(True)
        val_losses,val_metrics,val_distributions = step(False)
        vl = val_losses[0] + val_losses[1]
        for vm in val_metrics:
            vl += (-((vm['optimal_auc']*reward_weight) + (vm['imitation_auc']*imitation_weight)))/10
        if verbose:
            print('______epoch',str(epoch),'_____')
            print('val reward',val_losses[1].item())
            print('imitation reward', val_losses[0].item())
            print('distance losses',val_losses[2].item(),val_losses[-1].item())
            print('distributions',val_distributions)
            print(val_metrics)
        if vl < best_val_loss:
            best_val_loss = vl
            best_val_score = val_metrics
            best_val_distributions = val_distributions
            steps_since_improvement = 0
            torch.save(model.state_dict(),save_file)
        else:
            steps_since_improvement += 1
        if steps_since_improvement > patience:
            break
    print('++++++++++Final+++++++++++')
    print('best',best_val_loss)
    print(best_val_score)
    model.load_state_dict(torch.load(save_file))
    model.eval()
    return model, best_val_score, best_val_loss, best_val_distributions

from Models import *
args = {
    'hidden_layers': [1000,1000], 
    'opt_layer_size': 20, 
    'imitation_layer_size': 20, 
    'dropout': 0.25, 
    'input_dropout': 0.1, 
    'shufflecol_chance': 0.5
}

#1.8424
# decision_model, decision_score, decision_loss, _ 
rad_results = train_decision_model_triplet(
    rad_model1,rad_model2,rad_model3,rad_smodel3,
    dataset = rad_data,
    lr=.01,
    imitation_weight=1,
    reward_weight=1,
    patience=100,
    imitation_triplet_weight=0,
    reward_triplet_weight =0, 
    verbose=True,
    weights=[1,1,1,1], #realtive weight of survival, feeding tube, aspiration, andl lrc
    tweights=[1,1,1,0], #weight for OS, LRC, FDM, and event (any + FT or AS at 6m) as time to event in weeks
    use_attention=True,
    **args)

rad_results[2]

tensor([79., 49.,  0.]) 389
tensor([23., 22.,  0.]) 147
torch.Size([3, 536, 94])
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 0 _____
val reward 1.4960142374038696
imitation reward 2.0263779163360596
distance losses 0.0 0.0
distributions [0.006183651741594076, 0.007560078054666519, 0.0007955669425427914]
[{'decision': 0, 'optimal_auc': 0.7289621318373072, 'imitation_auc': 0.6340648854961832, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.6880000000000001, 'imitation_auc': 0.6160326086956522, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7736808645899556, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 1 _____
val reward 1.0062206983566284
imitation reward 1.2641663551330566
distance losses 0.0 0.0
distributions [0.06562148779630661, 0.01288602314889431, 0.00012579276517499238]
[{'decision': 0, 'optimal_auc': 0.7875175315568023, 'imitation_auc': 0.5090648854961832, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.8952727272727272, 'imitation_auc': 0.6532608695652173, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6776859504132231, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 2 _____
val reward 0.9166166186332703
imitation reward 1.2544894218444824
distance losses 0.0 0.0
distributions [0.44568654894828796, 0.06831824034452438, 9.297682117903605e-05]
[{'decision': 0, 'optimal_auc': 0.8011921458625527, 'imitation_auc': 0.4475190839694657, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9465454545454545, 'imitation_auc': 0.6850543478260869, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.7891156462585034}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7015257469802925, 'optimal_acc': 1.0, 'imitation_acc': 0.7074829931972789}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 3 _____
val reward 0.6280743479728699
imitation reward 1.1219018697738647
distance losses 0.0 0.0
distributions [0.18042628467082977, 0.19100430607795715, 1.9127091945847496e-05]
[{'decision': 0, 'optimal_auc': 0.8250350631136045, 'imitation_auc': 0.5658396946564884, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9545454545454546, 'imitation_auc': 0.6728260869565217, 'optimal_acc': 0.8775510204081632, 'imitation_acc': 0.7891156462585034}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7472981563890655, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 4 _____
val reward 0.7707536816596985
imitation reward 1.0946470499038696
distance losses 0.0 0.0
distributions [0.03471415862441063, 0.057200782001018524, 1.8811900872606202e-06]
[{'decision': 0, 'optimal_auc': 0.8211781206171108, 'imitation_auc': 0.6087786259541985, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9545454545454546, 'imitation_auc': 0.677445652173913, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.7891156462585034}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7536554354736172, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 5 _____
val reward 0.6744158864021301
imitation reward 1.1845349073410034
distance losses 0.0 0.0
distributions [0.28648921847343445, 0.2580718398094177, 1.9397220967221074e-06]
[{'decision': 0, 'optimal_auc': 0.8338008415147266, 'imitation_auc': 0.6159351145038168, 'optimal_acc': 0.8163265306122449, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9661818181818183, 'imitation_auc': 0.6771739130434783, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.7891156462585034}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7568340750158932, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 6 _____
val reward 0.5690086483955383
imitation reward 1.3518110513687134
distance losses 0.0 0.0
distributions [0.23282939195632935, 0.1102219894528389, 1.1730639926099684e-06]
[{'decision': 0, 'optimal_auc': 0.8316970546984572, 'imitation_auc': 0.6097328244274809, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9647272727272727, 'imitation_auc': 0.6831521739130435, 'optimal_acc': 0.9115646258503401, 'imitation_acc': 0.7006802721088435}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7549268912905277, 'optimal_acc': 1.0, 'imitation_acc': 0.6530612244897959}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 7 _____
val reward 0.6814818382263184
imitation reward 1.2299256324768066
distance losses 0.0 0.0
distributions [0.3274550437927246, 0.08481822162866592, 3.4256953540534596e-07]
[{'decision': 0, 'optimal_auc': 0.834852734922861, 'imitation_auc': 0.6078244274809161, 'optimal_acc': 0.7619047619047619, 'imitation_acc': 0.8843537414965986}, {'decision': 1, 'optimal_auc': 0.9694545454545455, 'imitation_auc': 0.6725543478260869, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8027210884353742}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7698664971392245, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 8 _____
val reward 0.5411596894264221
imitation reward 1.2146480083465576
distance losses 0.0 0.0
distributions [0.17273959517478943, 0.07653725147247314, 2.0266632816401398e-07]
[{'decision': 0, 'optimal_auc': 0.8338008415147266, 'imitation_auc': 0.6006679389312977, 'optimal_acc': 0.9047619047619048, 'imitation_acc': 0.8843537414965986}, {'decision': 1, 'optimal_auc': 0.9716363636363636, 'imitation_auc': 0.6733695652173913, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8027210884353742}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7803560076287349, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 9 _____
val reward 0.5083107948303223
imitation reward 1.1223291158676147
distance losses 0.0 0.0
distributions [0.09300429373979568, 0.12727731466293335, 3.00987920809348e-07]
[{'decision': 0, 'optimal_auc': 0.8359046283309958, 'imitation_auc': 0.6030534351145038, 'optimal_acc': 0.8775510204081632, 'imitation_acc': 0.8707482993197279}, {'decision': 1, 'optimal_auc': 0.9760000000000001, 'imitation_auc': 0.6720108695652174, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7883026064844245, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 10 _____
val reward 0.5093358755111694
imitation reward 1.1445863246917725
distance losses 0.0 0.0
distributions [0.13069643080234528, 0.2163611501455307, 4.857052999795997e-07]
[{'decision': 0, 'optimal_auc': 0.8383590462833099, 'imitation_auc': 0.6073473282442747, 'optimal_acc': 0.8775510204081632, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9810909090909091, 'imitation_auc': 0.6663043478260869, 'optimal_acc': 0.9183673469387755, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7902097902097903, 'optimal_acc': 1.0, 'imitation_acc': 0.8299319727891157}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 11 _____
val reward 0.5240051746368408
imitation reward 1.1609904766082764
distance losses 0.0 0.0
distributions [0.19628041982650757, 0.22638475894927979, 4.984258907825279e-07]
[{'decision': 0, 'optimal_auc': 0.8376577840112203, 'imitation_auc': 0.607824427480916, 'optimal_acc': 0.8979591836734694, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9832727272727273, 'imitation_auc': 0.6625, 'optimal_acc': 0.9047619047619048, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8022886204704387, 'optimal_acc': 1.0, 'imitation_acc': 0.8299319727891157}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 12 _____
val reward 0.4670889973640442
imitation reward 1.1589670181274414
distance losses 0.0 0.0
distributions [0.2066519409418106, 0.144403874874115, 3.7648570128112624e-07]
[{'decision': 0, 'optimal_auc': 0.8362552594670406, 'imitation_auc': 0.6054389312977099, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9818181818181818, 'imitation_auc': 0.65625, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8102352193261284, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 13 _____
val reward 0.5208724737167358
imitation reward 1.1517763137817383
distance losses 0.0 0.0
distributions [0.1936698704957962, 0.07349967956542969, 2.9567127057816833e-07]
[{'decision': 0, 'optimal_auc': 0.8408134642356241, 'imitation_auc': 0.5968511450381679, 'optimal_acc': 0.891156462585034, 'imitation_acc': 0.8707482993197279}, {'decision': 1, 'optimal_auc': 0.9807272727272727, 'imitation_auc': 0.6519021739130435, 'optimal_acc': 0.9047619047619048, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.819135410044501, 'optimal_acc': 1.0, 'imitation_acc': 0.8299319727891157}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 14 _____
val reward 0.4858075976371765
imitation reward 1.1699458360671997
distance losses 0.0 0.0
distributions [0.19797411561012268, 0.0930590108036995, 3.569035413875099e-07]
[{'decision': 0, 'optimal_auc': 0.8436185133239832, 'imitation_auc': 0.5939885496183206, 'optimal_acc': 0.8775510204081632, 'imitation_acc': 0.8503401360544217}, {'decision': 1, 'optimal_auc': 0.9832727272727273, 'imitation_auc': 0.6540760869565218, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8216783216783218, 'optimal_acc': 1.0, 'imitation_acc': 0.8367346938775511}]

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 15 _____
val reward 0.45085421204566956
imitation reward 1.2133344411849976
distance losses 0.0 0.0
distributions [0.21227982640266418, 0.16402383148670197, 3.919087703252444e-07]
[{'decision': 0, 'optimal_auc': 0.841164095371669, 'imitation_auc': 0.5935114503816794, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9872727272727273, 'imitation_auc': 0.6608695652173913, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8184996821360458, 'optimal_acc': 1.0, 'imitation_acc': 0.8639455782312925}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 16 _____
val reward 0.4848196506500244
imitation reward 1.2575812339782715
distance losses 0.0 0.0
distributions [0.18979278206825256, 0.21251678466796875, 3.019082157607045e-07]
[{'decision': 0, 'optimal_auc': 0.8418653576437587, 'imitation_auc': 0.5811068702290076, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8707482993197279}, {'decision': 1, 'optimal_auc': 0.9898181818181818, 'imitation_auc': 0.6630434782608696, 'optimal_acc': 0.9183673469387755, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8239033693579149, 'optimal_acc': 1.0, 'imitation_acc': 0.8639455782312925}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 17 _____
val reward 0.4563733637332916
imitation reward 1.2566475868225098
distance losses 0.0 0.0
distributions [0.12478204071521759, 0.1945611834526062, 2.1463763744122843e-07]
[{'decision': 0, 'optimal_auc': 0.8376577840112203, 'imitation_auc': 0.5825381679389313, 'optimal_acc': 0.8843537414965986, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9898181818181818, 'imitation_auc': 0.657608695652174, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8267641449459632, 'optimal_acc': 1.0, 'imitation_acc': 0.8503401360544217}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 18 _____
val reward 0.45774349570274353
imitation reward 1.235836148262024
distance losses 0.0 0.0
distributions [0.09379976987838745, 0.15588220953941345, 1.8355591180352349e-07]
[{'decision': 0, 'optimal_auc': 0.8355539971949509, 'imitation_auc': 0.5801526717557252, 'optimal_acc': 0.8843537414965986, 'imitation_acc': 0.8639455782312925}, {'decision': 1, 'optimal_auc': 0.9909090909090909, 'imitation_auc': 0.6573369565217391, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8273998728544183, 'optimal_acc': 1.0, 'imitation_acc': 0.8775510204081632}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 19 _____
val reward 0.43465369939804077
imitation reward 1.238765835762024
distance losses 0.0 0.0
distributions [0.13628676533699036, 0.1523745059967041, 3.2485056067343976e-07]
[{'decision': 0, 'optimal_auc': 0.8327489481065918, 'imitation_auc': 0.5825381679389313, 'optimal_acc': 0.8775510204081632, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9905454545454545, 'imitation_auc': 0.6682065217391304, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.826128417037508, 'optimal_acc': 1.0, 'imitation_acc': 0.8775510204081632}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 20 _____
val reward 0.455262154340744
imitation reward 1.270072340965271
distance losses 0.0 0.0
distributions [0.20817340910434723, 0.15767791867256165, 3.906968117917131e-07]
[{'decision': 0, 'optimal_auc': 0.8369565217391304, 'imitation_auc': 0.5887404580152671, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.992, 'imitation_auc': 0.6679347826086957, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.827717736808646, 'optimal_acc': 1.0, 'imitation_acc': 0.8775510204081632}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 21 _____
val reward 0.48130717873573303
imitation reward 1.3589799404144287
distance losses 0.0 0.0
distributions [0.23051582276821136, 0.16185933351516724, 3.260487346778973e-07]
[{'decision': 0, 'optimal_auc': 0.8394109396914446, 'imitation_auc': 0.5920801526717557, 'optimal_acc': 0.8299319727891157, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.992, 'imitation_auc': 0.6630434782608696, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7959183673469388}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8286713286713286, 'optimal_acc': 1.0, 'imitation_acc': 0.8639455782312925}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 22 _____
val reward 0.46929553151130676
imitation reward 1.3938324451446533
distance losses 0.0 0.0
distributions [0.2016780823469162, 0.16084258258342743, 3.2845974828887847e-07]
[{'decision': 0, 'optimal_auc': 0.8394109396914446, 'imitation_auc': 0.5958969465648856, 'optimal_acc': 0.8299319727891157, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9916363636363636, 'imitation_auc': 0.6663043478260869, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7959183673469388}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8264462809917354, 'optimal_acc': 1.0, 'imitation_acc': 0.8571428571428571}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 23 _____
val reward 0.46556368470191956
imitation reward 1.3671255111694336
distance losses 0.0 0.0
distributions [0.16242900490760803, 0.16595493257045746, 3.8326012941070076e-07]
[{'decision': 0, 'optimal_auc': 0.8380084151472651, 'imitation_auc': 0.5973282442748092, 'optimal_acc': 0.8843537414965986, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9923636363636363, 'imitation_auc': 0.6725543478260869, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8251748251748252, 'optimal_acc': 1.0, 'imitation_acc': 0.8571428571428571}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 24 _____
val reward 0.48034244775772095
imitation reward 1.371955394744873
distance losses 0.0 0.0
distributions [0.13167431950569153, 0.16900008916854858, 3.849856113902206e-07]
[{'decision': 0, 'optimal_auc': 0.83835904628331, 'imitation_auc': 0.5949427480916031, 'optimal_acc': 0.8843537414965986, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9923636363636363, 'imitation_auc': 0.6733695652173913, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8264462809917354, 'optimal_acc': 1.0, 'imitation_acc': 0.8503401360544217}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 25 _____
val reward 0.4962688088417053
imitation reward 1.4224181175231934
distance losses 0.0 0.0
distributions [0.1166837140917778, 0.17121393978595734, 3.1204646688820503e-07]
[{'decision': 0, 'optimal_auc': 0.8394109396914446, 'imitation_auc': 0.6049618320610687, 'optimal_acc': 0.8775510204081632, 'imitation_acc': 0.8707482993197279}, {'decision': 1, 'optimal_auc': 0.992, 'imitation_auc': 0.6741847826086956, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8194532739987286, 'optimal_acc': 1.0, 'imitation_acc': 0.8571428571428571}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 26 _____
val reward 0.49625343084335327
imitation reward 1.4854774475097656
distance losses 0.0 0.0
distributions [0.12940996885299683, 0.1753285825252533, 2.8654810080297466e-07]
[{'decision': 0, 'optimal_auc': 0.8390603085553997, 'imitation_auc': 0.5944656488549618, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9923636363636363, 'imitation_auc': 0.6717391304347826, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8150031786395423, 'optimal_acc': 1.0, 'imitation_acc': 0.8367346938775511}]

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 27 _____
val reward 0.49101492762565613
imitation reward 1.5292625427246094
distance losses 0.0 0.0
distributions [0.15132659673690796, 0.16662205755710602, 2.6552626763987064e-07]
[{'decision': 0, 'optimal_auc': 0.8373071528751753, 'imitation_auc': 0.5911259541984732, 'optimal_acc': 0.8843537414965986, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.993090909090909, 'imitation_auc': 0.6671195652173912, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8140495867768596, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 28 _____
val reward 0.5053893327713013
imitation reward 1.5667080879211426
distance losses 0.0 0.0
distributions [0.1822843849658966, 0.16037599742412567, 2.5695123895275174e-07]
[{'decision': 0, 'optimal_auc': 0.8359046283309959, 'imitation_auc': 0.5901717557251908, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9927272727272728, 'imitation_auc': 0.66875, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8048315321042594, 'optimal_acc': 1.0, 'imitation_acc': 0.8299319727891157}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 29 _____
val reward 0.5234814882278442
imitation reward 1.6723413467407227
distance losses 0.0 0.0
distributions [0.19644424319267273, 0.1533508598804474, 1.8199375517724548e-07]
[{'decision': 0, 'optimal_auc': 0.8320476858345022, 'imitation_auc': 0.5901717557251909, 'optimal_acc': 0.8163265306122449, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9916363636363636, 'imitation_auc': 0.6597826086956522, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8089637635092181, 'optimal_acc': 1.0, 'imitation_acc': 0.8367346938775511}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 30 _____
val reward 0.5280910730361938
imitation reward 1.7476398944854736
distance losses 0.0 0.0
distributions [0.18507759273052216, 0.14758335053920746, 1.2052025510911335e-07]
[{'decision': 0, 'optimal_auc': 0.8306451612903226, 'imitation_auc': 0.5834923664122138, 'optimal_acc': 0.8367346938775511, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9901818181818182, 'imitation_auc': 0.6456521739130434, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8095994914176732, 'optimal_acc': 1.0, 'imitation_acc': 0.8435374149659864}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 31 _____
val reward 0.5307213664054871
imitation reward 1.7483075857162476
distance losses 0.0 0.0
distributions [0.16691401600837708, 0.1424788385629654, 8.683696961497844e-08]
[{'decision': 0, 'optimal_auc': 0.8274894810659187, 'imitation_auc': 0.5749045801526718, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9894545454545455, 'imitation_auc': 0.6383152173913043, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8118245390972665, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 32 _____
val reward 0.5296931266784668
imitation reward 1.7978277206420898
distance losses 0.0 0.0
distributions [0.14976169168949127, 0.15597954392433167, 9.04718575611696e-08]
[{'decision': 0, 'optimal_auc': 0.8253856942496494, 'imitation_auc': 0.5701335877862594, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9898181818181818, 'imitation_auc': 0.6323369565217392, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8105530832803559, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 33 _____
val reward 0.537261426448822
imitation reward 1.8180842399597168
distance losses 0.0 0.0
distributions [0.1454937756061554, 0.1678994596004486, 7.035409765876466e-08]
[{'decision': 0, 'optimal_auc': 0.8239831697054698, 'imitation_auc': 0.5615458015267176, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8503401360544217}, {'decision': 1, 'optimal_auc': 0.9923636363636364, 'imitation_auc': 0.6402173913043477, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.812142403051494, 'optimal_acc': 1.0, 'imitation_acc': 0.8435374149659864}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 34 _____
val reward 0.5506553053855896
imitation reward 1.9308059215545654
distance losses 0.0 0.0
distributions [0.15520890057086945, 0.17871665954589844, 5.360439914170456e-08]
[{'decision': 0, 'optimal_auc': 0.8257363253856943, 'imitation_auc': 0.5605916030534351, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9941818181818182, 'imitation_auc': 0.6347826086956522, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8118245390972663, 'optimal_acc': 1.0, 'imitation_acc': 0.8435374149659864}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 35 _____
val reward 0.5460125803947449
imitation reward 2.0562703609466553
distance losses 0.0 0.0
distributions [0.1610439270734787, 0.16962240636348724, 3.755478417133418e-08]
[{'decision': 0, 'optimal_auc': 0.8295932678821879, 'imitation_auc': 0.5486641221374046, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9941818181818182, 'imitation_auc': 0.6146739130434782, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8130959949141767, 'optimal_acc': 1.0, 'imitation_acc': 0.8503401360544217}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 36 _____
val reward 0.5530176758766174
imitation reward 2.0035080909729004
distance losses 0.0 0.0
distributions [0.17220379412174225, 0.15716980397701263, 5.0388052841299213e-08]
[{'decision': 0, 'optimal_auc': 0.8306451612903226, 'imitation_auc': 0.5415076335877862, 'optimal_acc': 0.8299319727891157, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9938181818181817, 'imitation_auc': 0.6038043478260869, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.812142403051494, 'optimal_acc': 1.0, 'imitation_acc': 0.8299319727891157}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 37 _____
val reward 0.5634154081344604
imitation reward 1.9755091667175293
distance losses 0.0 0.0
distributions [0.1710202693939209, 0.14537471532821655, 4.981762202760365e-08]
[{'decision': 0, 'optimal_auc': 0.832398316970547, 'imitation_auc': 0.5348282442748091, 'optimal_acc': 0.8231292517006803, 'imitation_acc': 0.7959183673469388}, {'decision': 1, 'optimal_auc': 0.9934545454545454, 'imitation_auc': 0.6105978260869565, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8054672600127146, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 38 _____
val reward 0.571999192237854
imitation reward 2.025096893310547
distance losses 0.0 0.0
distributions [0.16650725901126862, 0.1387302428483963, 4.380657614433403e-08]
[{'decision': 0, 'optimal_auc': 0.8341514726507714, 'imitation_auc': 0.5400763358778626, 'optimal_acc': 0.8163265306122449, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.993090909090909, 'imitation_auc': 0.6043478260869565, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8019707565162111, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 39 _____
val reward 0.5694934129714966
imitation reward 2.10575795173645
distance losses 0.0 0.0
distributions [0.16536913812160492, 0.14255653321743011, 3.81949369909762e-08]
[{'decision': 0, 'optimal_auc': 0.8345021037868162, 'imitation_auc': 0.5481870229007634, 'optimal_acc': 0.8299319727891157, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.993090909090909, 'imitation_auc': 0.5997282608695652, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8032422123331214, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 40 _____
val reward 0.5703554749488831
imitation reward 2.2396161556243896
distance losses 0.0 0.0
distributions [0.16605646908283234, 0.14723193645477295, 2.4130708098368814e-08]
[{'decision': 0, 'optimal_auc': 0.8397615708274895, 'imitation_auc': 0.5486641221374046, 'optimal_acc': 0.8367346938775511, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9930909090909091, 'imitation_auc': 0.6005434782608696, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8102352193261284, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 41 _____
val reward 0.571012556552887
imitation reward 2.4309797286987305
distance losses 0.0 0.0
distributions [0.16508950293064117, 0.154286727309227, 1.630144019770796e-08]
[{'decision': 0, 'optimal_auc': 0.8446704067321178, 'imitation_auc': 0.5500954198473282, 'optimal_acc': 0.8367346938775511, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9923636363636363, 'imitation_auc': 0.5951086956521738, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8061029879211699, 'optimal_acc': 1.0, 'imitation_acc': 0.8435374149659864}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 42 _____
val reward 0.5856841206550598
imitation reward 2.435797929763794
distance losses 0.0 0.0
distributions [0.17185619473457336, 0.1709338277578354, 1.95928073765117e-08]
[{'decision': 0, 'optimal_auc': 0.8429172510518934, 'imitation_auc': 0.5567748091603053, 'optimal_acc': 0.8367346938775511, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9930909090909091, 'imitation_auc': 0.6032608695652174, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8000635727908456, 'optimal_acc': 1.0, 'imitation_acc': 0.8367346938775511}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 43 _____
val reward 0.5891621708869934
imitation reward 2.3689212799072266
distance losses 0.0 0.0
distributions [0.15930132567882538, 0.17020833492279053, 2.0715365423029652e-08]
[{'decision': 0, 'optimal_auc': 0.8404628330995791, 'imitation_auc': 0.5658396946564884, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9934545454545455, 'imitation_auc': 0.6027173913043479, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7914812460267006, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 44 _____
val reward 0.5870158076286316
imitation reward 2.374727725982666
distance losses 0.0 0.0
distributions [0.14583006501197815, 0.1600000262260437, 1.8089203024374e-08]
[{'decision': 0, 'optimal_auc': 0.8383590462833099, 'imitation_auc': 0.5768129770992366, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9923636363636363, 'imitation_auc': 0.5980978260869565, 'optimal_acc': 0.9863945578231292, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7902097902097902, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 45 _____
val reward 0.5989378690719604
imitation reward 2.4411330223083496
distance losses 0.0 0.0
distributions [0.14346732199192047, 0.1481214463710785, 1.1401131594368508e-08]
[{'decision': 0, 'optimal_auc': 0.8443197755960729, 'imitation_auc': 0.5782442748091603, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.992, 'imitation_auc': 0.5932065217391304, 'optimal_acc': 0.9863945578231292, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7952956134774316, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 46 _____
val reward 0.6190824508666992
imitation reward 2.5891547203063965
distance losses 0.0 0.0
distributions [0.14939679205417633, 0.13969536125659943, 7.73692576672147e-09]
[{'decision': 0, 'optimal_auc': 0.8460729312762973, 'imitation_auc': 0.5753816793893131, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.992, 'imitation_auc': 0.5899456521739131, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7968849332485697, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 47 _____
val reward 0.6306546330451965
imitation reward 2.608410596847534
distance losses 0.0 0.0
distributions [0.16136489808559418, 0.13864998519420624, 7.262660695062095e-09]
[{'decision': 0, 'optimal_auc': 0.8457223001402525, 'imitation_auc': 0.5625, 'optimal_acc': 0.8367346938775511, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9923636363636363, 'imitation_auc': 0.5945652173913043, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.799745708836618, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 48 _____
val reward 0.6376725435256958
imitation reward 2.6717424392700195
distance losses 0.0 0.0
distributions [0.16480332612991333, 0.13981400430202484, 7.089540510207826e-09]
[{'decision': 0, 'optimal_auc': 0.8443197755960729, 'imitation_auc': 0.5577290076335878, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9923636363636363, 'imitation_auc': 0.5826086956521739, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7987921169739352, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 49 _____
val reward 0.6303208470344543
imitation reward 2.6635231971740723
distance losses 0.0 0.0
distributions [0.16711999475955963, 0.1504911184310913, 8.483314495322247e-09]
[{'decision': 0, 'optimal_auc': 0.8401122019635343, 'imitation_auc': 0.5591603053435115, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9938181818181818, 'imitation_auc': 0.5779891304347826, 'optimal_acc': 0.9863945578231292, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7921169739351557, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 50 _____
val reward 0.6251764893531799
imitation reward 2.7412991523742676
distance losses 0.0 0.0
distributions [0.1481054276227951, 0.16164885461330414, 9.07549679851627e-09]
[{'decision': 0, 'optimal_auc': 0.8394109396914445, 'imitation_auc': 0.565601145038168, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9941818181818182, 'imitation_auc': 0.5684782608695653, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7927527018436109, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 51 _____
val reward 0.638163149356842
imitation reward 2.795691728591919
distance losses 0.0 0.0
distributions [0.1309516578912735, 0.17250226438045502, 9.361569297539063e-09]
[{'decision': 0, 'optimal_auc': 0.8394109396914446, 'imitation_auc': 0.5710877862595419, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9941818181818182, 'imitation_auc': 0.5679347826086957, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7937062937062938, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 52 _____
val reward 0.6476528644561768
imitation reward 2.784614086151123
distance losses 0.0 0.0
distributions [0.1337180733680725, 0.17456646263599396, 9.30515664521181e-09]
[{'decision': 0, 'optimal_auc': 0.8380084151472651, 'imitation_auc': 0.5713263358778625, 'optimal_acc': 0.8367346938775511, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9945454545454546, 'imitation_auc': 0.5798913043478261, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7873490146217419, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 53 _____
val reward 0.6464583277702332
imitation reward 2.781214475631714
distance losses 0.0 0.0
distributions [0.15831966698169708, 0.16799214482307434, 7.62736718229462e-09]
[{'decision': 0, 'optimal_auc': 0.8362552594670406, 'imitation_auc': 0.5696564885496183, 'optimal_acc': 0.8163265306122449, 'imitation_acc': 0.8503401360544217}, {'decision': 1, 'optimal_auc': 0.9945454545454546, 'imitation_auc': 0.59375, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7844882390336936, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 54 _____
val reward 0.6607720851898193
imitation reward 2.8997130393981934
distance losses 0.0 0.0
distributions [0.18475496768951416, 0.1584128886461258, 5.886528597898177e-09]
[{'decision': 0, 'optimal_auc': 0.8362552594670406, 'imitation_auc': 0.5641698473282443, 'optimal_acc': 0.8367346938775511, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9934545454545455, 'imitation_auc': 0.5907608695652175, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7892561983471074, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 55 _____
val reward 0.691981315612793
imitation reward 2.9604415893554688
distance losses 0.0 0.0
distributions [0.20786000788211823, 0.15280604362487793, 6.072978120386097e-09]
[{'decision': 0, 'optimal_auc': 0.8380084151472651, 'imitation_auc': 0.5629770992366412, 'optimal_acc': 0.8231292517006803, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9930909090909091, 'imitation_auc': 0.5880434782608696, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7876668785759695, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 56 _____
val reward 0.6891692876815796
imitation reward 3.058241367340088
distance losses 0.0 0.0
distributions [0.1912633180618286, 0.14620743691921234, 5.777309741716863e-09]
[{'decision': 0, 'optimal_auc': 0.8373071528751753, 'imitation_auc': 0.5653625954198473, 'optimal_acc': 0.8299319727891157, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9923636363636364, 'imitation_auc': 0.5625, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7857596948506039, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 57 _____
val reward 0.6833552122116089
imitation reward 3.146181344985962
distance losses 0.0 0.0
distributions [0.1628708392381668, 0.14585834741592407, 5.884485787532867e-09]
[{'decision': 0, 'optimal_auc': 0.8376577840112203, 'imitation_auc': 0.5713263358778626, 'optimal_acc': 0.8299319727891157, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9927272727272728, 'imitation_auc': 0.5375, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7816274634456453, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 58 _____
val reward 0.685442328453064
imitation reward 3.1578547954559326
distance losses 0.0 0.0
distributions [0.15265928208827972, 0.14844836294651031, 6.937626473302316e-09]
[{'decision': 0, 'optimal_auc': 0.8327489481065918, 'imitation_auc': 0.575381679389313, 'optimal_acc': 0.8367346938775511, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9938181818181818, 'imitation_auc': 0.5383152173913043, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7822631913541005, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 59 _____
val reward 0.685879647731781
imitation reward 3.113774299621582
distance losses 0.0 0.0
distributions [0.14392992854118347, 0.15189538896083832, 7.3616326368153295e-09]
[{'decision': 0, 'optimal_auc': 0.8341514726507714, 'imitation_auc': 0.5756202290076337, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.9941818181818183, 'imitation_auc': 0.5470108695652174, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7835346471710107, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 60 _____
val reward 0.6780730485916138
imitation reward 3.061758041381836
distance losses 0.0 0.0
distributions [0.14983774721622467, 0.15866254270076752, 7.730503348568618e-09]
[{'decision': 0, 'optimal_auc': 0.8338008415147264, 'imitation_auc': 0.5799141221374046, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.994909090909091, 'imitation_auc': 0.5567934782608696, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7870311506675143, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 61 _____
val reward 0.6690806746482849
imitation reward 3.026914119720459
distance losses 0.0 0.0
distributions [0.16345414519309998, 0.1628556251525879, 7.12572090222352e-09]
[{'decision': 0, 'optimal_auc': 0.8373071528751752, 'imitation_auc': 0.58206106870229, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.996, 'imitation_auc': 0.5665760869565217, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7870311506675143, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 62 _____
val reward 0.6579627394676208
imitation reward 3.0266213417053223
distance losses 0.0 0.0
distributions [0.170515775680542, 0.1597713679075241, 6.065640878460954e-09]
[{'decision': 0, 'optimal_auc': 0.8387096774193548, 'imitation_auc': 0.5844465648854963, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8503401360544217}, {'decision': 1, 'optimal_auc': 0.9956363636363637, 'imitation_auc': 0.5793478260869565, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7844882390336936, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 63 _____
val reward 0.6458596587181091
imitation reward 3.1445415019989014
distance losses 0.0 0.0
distributions [0.1642579436302185, 0.15304513275623322, 4.34343672139903e-09]
[{'decision': 0, 'optimal_auc': 0.8432678821879382, 'imitation_auc': 0.5825381679389313, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9952727272727273, 'imitation_auc': 0.5709239130434782, 'optimal_acc': 0.9863945578231292, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7835346471710108, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 64 _____
val reward 0.6516125798225403
imitation reward 3.3115386962890625
distance losses 0.0 0.0
distributions [0.1482512354850769, 0.14171072840690613, 2.941488830288108e-09]
[{'decision': 0, 'optimal_auc': 0.8488779803646563, 'imitation_auc': 0.5870706106870229, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8503401360544217}, {'decision': 1, 'optimal_auc': 0.994909090909091, 'imitation_auc': 0.5619565217391305, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7851239669421488, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 65 _____
val reward 0.6582897305488586
imitation reward 3.400123119354248
distance losses 0.0 0.0
distributions [0.14453279972076416, 0.13697458803653717, 2.6122364271685683e-09]
[{'decision': 0, 'optimal_auc': 0.8506311360448808, 'imitation_auc': 0.5870706106870229, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9941818181818182, 'imitation_auc': 0.5573369565217391, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7841703750794661, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 66 _____
val reward 0.6572396755218506
imitation reward 3.430911064147949
distance losses 0.0 0.0
distributions [0.14603903889656067, 0.1408185362815857, 2.7691198223323e-09]
[{'decision': 0, 'optimal_auc': 0.8534361851332398, 'imitation_auc': 0.5906488549618321, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9945454545454546, 'imitation_auc': 0.5559782608695653, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7794024157660522, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 67 _____
val reward 0.661010205745697
imitation reward 3.4145383834838867
distance losses 0.0 0.0
distributions [0.16660404205322266, 0.1495223045349121, 3.062509135176583e-09]
[{'decision': 0, 'optimal_auc': 0.8534361851332398, 'imitation_auc': 0.5904103053435115, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9938181818181818, 'imitation_auc': 0.5567934782608696, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7759059122695486, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 68 _____
val reward 0.6667952537536621
imitation reward 3.351165771484375
distance losses 0.0 0.0
distributions [0.17156930267810822, 0.15684771537780762, 3.0053950439423716e-09]
[{'decision': 0, 'optimal_auc': 0.8562412342215988, 'imitation_auc': 0.589456106870229, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9934545454545455, 'imitation_auc': 0.5597826086956522, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7765416401780038, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 69 _____
val reward 0.6622213125228882
imitation reward 3.280794620513916
distance losses 0.0 0.0
distributions [0.15215252339839935, 0.16073429584503174, 2.90170643069132e-09]
[{'decision': 0, 'optimal_auc': 0.8541374474053296, 'imitation_auc': 0.5942270992366412, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.8503401360544217}, {'decision': 1, 'optimal_auc': 0.9930909090909091, 'imitation_auc': 0.5584239130434783, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7762237762237763, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 70 _____
val reward 0.6695631146430969
imitation reward 3.5961151123046875
distance losses 0.0 0.0
distributions [0.13277922570705414, 0.16217464208602905, 2.6200337455151157e-09]
[{'decision': 0, 'optimal_auc': 0.8548387096774194, 'imitation_auc': 0.5935114503816794, 'optimal_acc': 0.891156462585034, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9934545454545455, 'imitation_auc': 0.5480978260869566, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7759059122695486, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 71 _____
val reward 0.6796318888664246
imitation reward 3.636445999145508
distance losses 0.0 0.0
distributions [0.12950710952281952, 0.1585109531879425, 2.3140651617126196e-09]
[{'decision': 0, 'optimal_auc': 0.8569424964936886, 'imitation_auc': 0.5947041984732824, 'optimal_acc': 0.891156462585034, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9923636363636363, 'imitation_auc': 0.5407608695652174, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7803560076287348, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 72 _____
val reward 0.6922823786735535
imitation reward 3.4112548828125
distance losses 0.0 0.0
distributions [0.14204663038253784, 0.1543908715248108, 2.150490230334867e-09]
[{'decision': 0, 'optimal_auc': 0.8548387096774194, 'imitation_auc': 0.6001908396946565, 'optimal_acc': 0.9047619047619048, 'imitation_acc': 0.8639455782312925}, {'decision': 1, 'optimal_auc': 0.9916363636363636, 'imitation_auc': 0.5309782608695652, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7848061029879212, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 73 _____
val reward 0.7154828906059265
imitation reward 3.4859871864318848
distance losses 0.0 0.0
distributions [0.15430712699890137, 0.15062256157398224, 2.0024355507075597e-09]
[{'decision': 0, 'optimal_auc': 0.8506311360448808, 'imitation_auc': 0.6080629770992366, 'optimal_acc': 0.8843537414965986, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9890909090909091, 'imitation_auc': 0.5277173913043478, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7943420216147489, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 74 _____
val reward 0.7321478724479675
imitation reward 3.531968116760254
distance losses 0.0 0.0
distributions [0.18080586194992065, 0.15052850544452667, 2.4494093420202034e-09]
[{'decision': 0, 'optimal_auc': 0.850280504908836, 'imitation_auc': 0.6044847328244275, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9898181818181819, 'imitation_auc': 0.525, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7952956134774316, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 75 _____
val reward 0.720704197883606
imitation reward 3.542299747467041
distance losses 0.0 0.0
distributions [0.1807674616575241, 0.15251590311527252, 3.163336925737781e-09]
[{'decision': 0, 'optimal_auc': 0.8520336605890603, 'imitation_auc': 0.6063931297709924, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.990909090909091, 'imitation_auc': 0.5323369565217391, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.79815638906548, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 76 _____
val reward 0.7052645087242126
imitation reward 3.527566432952881
distance losses 0.0 0.0
distributions [0.16785617172718048, 0.15682412683963776, 4.098939854202399e-09]
[{'decision': 0, 'optimal_auc': 0.8509817671809256, 'imitation_auc': 0.6063931297709924, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9912727272727273, 'imitation_auc': 0.5383152173913044, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7949777495232041, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 77 _____
val reward 0.6945423483848572
imitation reward 3.452005386352539
distance losses 0.0 0.0
distributions [0.16277550160884857, 0.1611539125442505, 5.426389559914924e-09]
[{'decision': 0, 'optimal_auc': 0.8474754558204768, 'imitation_auc': 0.6001908396946565, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.992, 'imitation_auc': 0.5519021739130434, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7956134774316592, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 78 _____
val reward 0.69114750623703
imitation reward 3.7320470809936523
distance losses 0.0 0.0
distributions [0.1553187221288681, 0.16519704461097717, 7.213401431727107e-09]
[{'decision': 0, 'optimal_auc': 0.8436185133239832, 'imitation_auc': 0.5999522900763358, 'optimal_acc': 0.8367346938775511, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9938181818181818, 'imitation_auc': 0.5494565217391304, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7962492053401145, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 79 _____
val reward 0.6995605826377869
imitation reward 3.722728729248047
distance losses 0.0 0.0
distributions [0.17005571722984314, 0.17095178365707397, 9.197361983126484e-09]
[{'decision': 0, 'optimal_auc': 0.8429172510518934, 'imitation_auc': 0.5987595419847328, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9952727272727272, 'imitation_auc': 0.5491847826086956, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7978385251112523, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 80 _____
val reward 0.7015296220779419
imitation reward 3.7254037857055664
distance losses 0.0 0.0
distributions [0.1797717809677124, 0.16970805823802948, 9.988201377097994e-09]
[{'decision': 0, 'optimal_auc': 0.8429172510518934, 'imitation_auc': 0.59375, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9949090909090909, 'imitation_auc': 0.5394021739130436, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7278911564625851}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7975206611570248, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 81 _____
val reward 0.6961716413497925
imitation reward 3.748504161834717
distance losses 0.0 0.0
distributions [0.16441389918327332, 0.1638939380645752, 1.0965577779131763e-08]
[{'decision': 0, 'optimal_auc': 0.8429172510518934, 'imitation_auc': 0.5896946564885496, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8639455782312925}, {'decision': 1, 'optimal_auc': 0.9949090909090909, 'imitation_auc': 0.5293478260869565, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7278911564625851}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7962492053401145, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 82 _____
val reward 0.7011839747428894
imitation reward 3.7945783138275146
distance losses 0.0 0.0
distributions [0.1521555781364441, 0.1577145904302597, 9.117682608916766e-09]
[{'decision': 0, 'optimal_auc': 0.8481767180925666, 'imitation_auc': 0.5899332061068703, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9945454545454545, 'imitation_auc': 0.5293478260869565, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7984742530197075, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 83 _____
val reward 0.7203263640403748
imitation reward 3.8715059757232666
distance losses 0.0 0.0
distributions [0.13908931612968445, 0.1462777853012085, 7.682820601928597e-09]
[{'decision': 0, 'optimal_auc': 0.8576437587657785, 'imitation_auc': 0.5901717557251908, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9945454545454545, 'imitation_auc': 0.5277173913043479, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7278911564625851}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8019707565162111, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 84 _____
val reward 0.7136674523353577
imitation reward 3.878349542617798
distance losses 0.0 0.0
distributions [0.14310938119888306, 0.1438070833683014, 8.990366673344852e-09]
[{'decision': 0, 'optimal_auc': 0.8618513323983169, 'imitation_auc': 0.5973282442748091, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9941818181818182, 'imitation_auc': 0.53125, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7278911564625851}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8080101716465353, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 85 _____
val reward 0.7000844478607178
imitation reward 3.878854513168335
distance losses 0.0 0.0
distributions [0.1555715948343277, 0.14972811937332153, 1.5557450439018794e-08]
[{'decision': 0, 'optimal_auc': 0.8604488078541375, 'imitation_auc': 0.5904103053435115, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9941818181818182, 'imitation_auc': 0.5358695652173913, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8026064844246663, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 86 _____
val reward 0.691260039806366
imitation reward 3.889516830444336
distance losses 0.0 0.0
distributions [0.15887045860290527, 0.15351903438568115, 2.0526918831365037e-08]
[{'decision': 0, 'optimal_auc': 0.861851332398317, 'imitation_auc': 0.5911259541984732, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9945454545454545, 'imitation_auc': 0.5364130434782608, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8035600762873489, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 87 _____
val reward 0.6822590231895447
imitation reward 3.9738149642944336
distance losses 0.0 0.0
distributions [0.1546354740858078, 0.1583145558834076, 2.1564963148534844e-08]
[{'decision': 0, 'optimal_auc': 0.861500701262272, 'imitation_auc': 0.5825381679389313, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8639455782312925}, {'decision': 1, 'optimal_auc': 0.9945454545454545, 'imitation_auc': 0.5317934782608695, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8013350286077559, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 88 _____
val reward 0.6778626441955566
imitation reward 4.047439098358154
distance losses 0.0 0.0
distributions [0.13786737620830536, 0.16136561334133148, 1.656859893728324e-08]
[{'decision': 0, 'optimal_auc': 0.8597475455820476, 'imitation_auc': 0.5763358778625953, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8639455782312925}, {'decision': 1, 'optimal_auc': 0.994909090909091, 'imitation_auc': 0.5233695652173913, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8045136681500318, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 89 _____
val reward 0.6839020252227783
imitation reward 3.89265775680542
distance losses 0.0 0.0
distributions [0.13237570226192474, 0.16247594356536865, 1.635049606818484e-08]
[{'decision': 0, 'optimal_auc': 0.8541374474053296, 'imitation_auc': 0.5756202290076335, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9945454545454546, 'imitation_auc': 0.5282608695652173, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8073744437380801, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 90 _____
val reward 0.6873904466629028
imitation reward 3.7375168800354004
distance losses 0.0 0.0
distributions [0.12977392971515656, 0.15901710093021393, 1.785581105195888e-08]
[{'decision': 0, 'optimal_auc': 0.8506311360448807, 'imitation_auc': 0.567986641221374, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9945454545454546, 'imitation_auc': 0.5285326086956521, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8086458995549906, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 91 _____
val reward 0.6884966492652893
imitation reward 3.5808043479919434
distance losses 0.0 0.0
distributions [0.13294799625873566, 0.15361489355564117, 1.8891876507609595e-08]
[{'decision': 0, 'optimal_auc': 0.8453716690042076, 'imitation_auc': 0.5560591603053435, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9941818181818182, 'imitation_auc': 0.5353260869565217, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8089637635092181, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 92 _____
val reward 0.6950863003730774
imitation reward 3.509874105453491
distance losses 0.0 0.0
distributions [0.1383001059293747, 0.1499512791633606, 1.7914777217242772e-08]
[{'decision': 0, 'optimal_auc': 0.8397615708274896, 'imitation_auc': 0.5462786259541985, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9934545454545455, 'imitation_auc': 0.5358695652173913, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8067387158296249, 'optimal_acc': 1.0, 'imitation_acc': 0.8299319727891157}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 93 _____
val reward 0.7009087800979614
imitation reward 3.5373024940490723
distance losses 0.0 0.0
distributions [0.15763482451438904, 0.1473248451948166, 1.4403909176508023e-08]
[{'decision': 0, 'optimal_auc': 0.8369565217391305, 'imitation_auc': 0.541030534351145, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9930909090909091, 'imitation_auc': 0.5323369565217391, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.805149396058487, 'optimal_acc': 1.0, 'imitation_acc': 0.8299319727891157}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 94 _____
val reward 0.7128694653511047
imitation reward 3.5820398330688477
distance losses 0.0 0.0
distributions [0.17430612444877625, 0.14811861515045166, 1.3114656916002332e-08]
[{'decision': 0, 'optimal_auc': 0.8387096774193549, 'imitation_auc': 0.5407919847328244, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9934545454545455, 'imitation_auc': 0.5391304347826087, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8070565797838525, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 95 _____
val reward 0.7149008512496948
imitation reward 3.6055374145507812
distance losses 0.0 0.0
distributions [0.17417404055595398, 0.1535961627960205, 1.3703141732435142e-08]
[{'decision': 0, 'optimal_auc': 0.835203366058906, 'imitation_auc': 0.5302958015267175, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9934545454545455, 'imitation_auc': 0.5451086956521739, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8022886204704387, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 96 _____
val reward 0.7182673215866089
imitation reward 3.5955286026000977
distance losses 0.0 0.0
distributions [0.17068913578987122, 0.15872594714164734, 1.5381967699568122e-08]
[{'decision': 0, 'optimal_auc': 0.8327489481065918, 'imitation_auc': 0.5279103053435115, 'optimal_acc': 0.8435374149659864, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.994909090909091, 'imitation_auc': 0.5529891304347826, 'optimal_acc': 0.9795918367346939, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8006993006993006, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 97 _____
val reward 0.7181521058082581
imitation reward 3.572571277618408
distance losses 0.0 0.0
distributions [0.16162456572055817, 0.1623794287443161, 1.645169867003915e-08]
[{'decision': 0, 'optimal_auc': 0.8309957924263675, 'imitation_auc': 0.5348282442748092, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.994909090909091, 'imitation_auc': 0.5595108695652175, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7952956134774316, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 98 _____
val reward 0.7282095551490784
imitation reward 3.5258164405822754
distance losses 0.0 0.0
distributions [0.15320192277431488, 0.16894857585430145, 1.9262516914864136e-08]
[{'decision': 0, 'optimal_auc': 0.8302945301542777, 'imitation_auc': 0.5393606870229007, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9949090909090909, 'imitation_auc': 0.5758152173913044, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.792752701843611, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 99 _____
val reward 0.7418086528778076
imitation reward 3.5277793407440186
distance losses 0.0 0.0
distributions [0.15346616506576538, 0.17220622301101685, 1.9871528422754636e-08]
[{'decision': 0, 'optimal_auc': 0.8299438990182327, 'imitation_auc': 0.5384064885496183, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9949090909090909, 'imitation_auc': 0.579891304347826, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7278911564625851}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7930705657978385, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 100 _____
val reward 0.7561330795288086
imitation reward 3.5767195224761963
distance losses 0.0 0.0
distributions [0.151222825050354, 0.17450034618377686, 1.8732773554575033e-08]
[{'decision': 0, 'optimal_auc': 0.8292426367461431, 'imitation_auc': 0.5369751908396946, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9941818181818182, 'imitation_auc': 0.5807065217391304, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7278911564625851}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7844882390336936, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 101 _____
val reward 0.7678948044776917
imitation reward 3.6290059089660645
distance losses 0.0 0.0
distributions [0.1539352685213089, 0.17241762578487396, 1.6163347993369825e-08]
[{'decision': 0, 'optimal_auc': 0.829242636746143, 'imitation_auc': 0.5379293893129771, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9934545454545454, 'imitation_auc': 0.5793478260869566, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7832167832167832, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 102 _____
val reward 0.7874733209609985
imitation reward 3.666933059692383
distance losses 0.0 0.0
distributions [0.1570754051208496, 0.1713656336069107, 1.4670278325468189e-08]
[{'decision': 0, 'optimal_auc': 0.8281907433380085, 'imitation_auc': 0.5405534351145039, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9927272727272727, 'imitation_auc': 0.575, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7797202797202797, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 103 _____
val reward 0.8000234961509705
imitation reward 3.715172290802002
distance losses 0.0 0.0
distributions [0.15621791779994965, 0.16608139872550964, 1.3256824082930052e-08]
[{'decision': 0, 'optimal_auc': 0.8274894810659187, 'imitation_auc': 0.5355438931297709, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.9923636363636363, 'imitation_auc': 0.5722826086956522, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.778766687857597, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 104 _____
val reward 0.8133997321128845
imitation reward 3.711245536804199
distance losses 0.0 0.0
distributions [0.15417931973934174, 0.16108588874340057, 1.3563917988790308e-08]
[{'decision': 0, 'optimal_auc': 0.8271388499298737, 'imitation_auc': 0.5360209923664122, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.9912727272727273, 'imitation_auc': 0.5709239130434782, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.775588048315321, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 105 _____
val reward 0.8277238011360168
imitation reward 3.71506404876709
distance losses 0.0 0.0
distributions [0.15428628027439117, 0.15560850501060486, 1.4480757926094157e-08]
[{'decision': 0, 'optimal_auc': 0.8278401122019635, 'imitation_auc': 0.5381679389312977, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9901818181818183, 'imitation_auc': 0.5641304347826087, 'optimal_acc': 0.9659863945578231, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7771773680864589, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 106 _____
val reward 0.8356059193611145
imitation reward 3.7116594314575195
distance losses 0.0 0.0
distributions [0.15801934897899628, 0.15686877071857452, 1.689846484964619e-08]
[{'decision': 0, 'optimal_auc': 0.8292426367461431, 'imitation_auc': 0.5362595419847328, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9898181818181818, 'imitation_auc': 0.560054347826087, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.778766687857597, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 107 _____
val reward 0.8399924039840698
imitation reward 3.6732017993927
distance losses 0.0 0.0
distributions [0.15333232283592224, 0.15700508654117584, 2.004760268903283e-08]
[{'decision': 0, 'optimal_auc': 0.8285413744740533, 'imitation_auc': 0.5364980916030535, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9894545454545455, 'imitation_auc': 0.5570652173913044, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.778766687857597, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 108 _____
val reward 0.8432106375694275
imitation reward 3.6855416297912598
distance losses 0.0 0.0
distributions [0.15249145030975342, 0.15860040485858917, 2.2222431894647343e-08]
[{'decision': 0, 'optimal_auc': 0.8281907433380085, 'imitation_auc': 0.533158396946565, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9894545454545455, 'imitation_auc': 0.5508152173913043, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7822631913541005, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 109 _____
val reward 0.8413839340209961
imitation reward 3.702411651611328
distance losses 0.0 0.0
distributions [0.16412636637687683, 0.15709610283374786, 2.4186197933318e-08]
[{'decision': 0, 'optimal_auc': 0.8295932678821879, 'imitation_auc': 0.5350667938931297, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9909090909090909, 'imitation_auc': 0.5407608695652174, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7867132867132867, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 110 _____
val reward 0.8428277373313904
imitation reward 3.6806254386901855
distance losses 0.0 0.0
distributions [0.1719760149717331, 0.14877749979496002, 2.1217035239828874e-08]
[{'decision': 0, 'optimal_auc': 0.829943899018233, 'imitation_auc': 0.5388835877862594, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9898181818181817, 'imitation_auc': 0.5429347826086957, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7902097902097902, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]

tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 111 _____
val reward 0.8404582738876343
imitation reward 3.668358325958252
distance losses 0.0 0.0
distributions [0.17303594946861267, 0.14564195275306702, 1.863332066420753e-08]
[{'decision': 0, 'optimal_auc': 0.8288920056100982, 'imitation_auc': 0.5491412213740459, 'optimal_acc': 0.8503401360544217, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9905454545454545, 'imitation_auc': 0.5418478260869565, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7937062937062938, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 112 _____
val reward 0.84120112657547
imitation reward 3.6963701248168945
distance losses 0.0 0.0
distributions [0.17409701645374298, 0.14449159801006317, 1.5704861411336424e-08]
[{'decision': 0, 'optimal_auc': 0.8292426367461431, 'imitation_auc': 0.5512881679389313, 'optimal_acc': 0.8571428571428571, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9905454545454545, 'imitation_auc': 0.5423913043478261, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7278911564625851}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7927527018436109, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.1565, 0.1497, 0.0000], grad_fn=<MeanBackward1>)
______epoch 113 _____
val reward 0.8374626636505127
imitation reward 3.740879535675049
distance losses 0.0 0.0
distributions [0.16785919666290283, 0.14108394086360931, 1.1647617981225267e-08]
[{'decision': 0, 'optimal_auc': 0.8292426367461431, 'imitation_auc': 0.5577290076335877, 'optimal_acc': 0.8639455782312925, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9905454545454545, 'imitation_auc': 0.5423913043478261, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7210884353741497}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7978385251112524, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
++++++++++Final+++++++++++
best tensor(1.3371, grad_fn=<AddBackward0>)
[{'decision': 0, 'optimal_auc': 0.8362552594670406, 'imitation_auc': 0.6054389312977099, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9818181818181818, 'imitation_auc': 0.65625, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8102352193261284, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]

/tmp/ipykernel_2619893/3871624404.py:355: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(save_file))

tensor(1.3371, grad_fn=<AddBackward0>)

In [26]:
pd.DataFrame(rad_results[1])

   decision  optimal_auc  imitation_auc  optimal_acc  imitation_acc
0         0     0.869215       0.588740     0.877551       0.891156
1         1     0.983636       0.651359     0.911565       0.734694
2         2    -1.000000       0.792117     1.000000       0.816327

In [33]:
control_results = train_decision_model_triplet(
    control_model1,control_model2,control_model3,control_smodel3,
    dataset=control_data,
    lr=.01,
    imitation_weight=1,
    reward_weight=1,
    patience=100,
    imitation_triplet_weight=0,
    reward_triplet_weight =0, 
    verbose=True,
    weights=[1,1,1,1], #realtive weight of survival, feeding tube, aspiration, andl lrc
    tweights=[1,1,1,0], #weight for OS, LRC, FDM, and event (any + FT or AS at 6m) as time to event in weeks
    use_attention=True,
    **args)

control_results[2]

tensor([246.,  91.,   0.]) 389
tensor([89., 37.,  0.]) 147
torch.Size([3, 536, 86])
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 0 _____
val reward 1.6990019083023071
imitation reward 2.0547354221343994
distance losses 0.0 0.0
distributions [0.7937368750572205, 0.014970784075558186, 0.001257091760635376]
[{'decision': 0, 'optimal_auc': 0.6381247578457963, 'imitation_auc': 0.6221374045801527, 'optimal_acc': 0.6054421768707483, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9422604422604424, 'imitation_auc': 0.6152173913043478, 'optimal_acc': 0.7482993197278912, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7848061029879212, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 1 _____
val reward 1.4893807172775269
imitation reward 1.6024320125579834
distance losses 0.0 0.0
distributions [0.16329051554203033, 0.2437649369239807, 0.00013056083116680384]
[{'decision': 0, 'optimal_auc': 0.6512979465323518, 'imitation_auc': 0.45109732824427484, 'optimal_acc': 0.3945578231292517, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9589680589680589, 'imitation_auc': 0.6755434782608696, 'optimal_acc': 0.8775510204081632, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7323585505403687, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 2 _____
val reward 0.992939829826355
imitation reward 1.1258761882781982
distance losses 0.0 0.0
distributions [0.7898318767547607, 0.22550813853740692, 7.401938637485728e-05]
[{'decision': 0, 'optimal_auc': 0.6017047655947306, 'imitation_auc': 0.370706106870229, 'optimal_acc': 0.6054421768707483, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9864864864864864, 'imitation_auc': 0.6894021739130435, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7891156462585034}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7177368086458995, 'optimal_acc': 1.0, 'imitation_acc': 0.8231292517006803}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 3 _____
val reward 0.9194592237472534
imitation reward 1.251430630683899
distance losses 0.0 0.0
distributions [0.782744824886322, 0.25040745735168457, 2.9896369596826844e-05]
[{'decision': 0, 'optimal_auc': 0.5854320030995738, 'imitation_auc': 0.42461832061068705, 'optimal_acc': 0.6054421768707483, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9911547911547911, 'imitation_auc': 0.6970108695652173, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.6666666666666666}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7447552447552448, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 4 _____
val reward 0.9664444923400879
imitation reward 1.1743260622024536
distance losses 0.0 0.0
distributions [0.5982366800308228, 0.4029005169868469, 7.084146545821568e-06]
[{'decision': 0, 'optimal_auc': 0.5385509492444789, 'imitation_auc': 0.5777671755725191, 'optimal_acc': 0.564625850340136, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9916461916461917, 'imitation_auc': 0.6948369565217392, 'optimal_acc': 0.8707482993197279, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7914812460267007, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 5 _____
val reward 1.1010020971298218
imitation reward 1.2165451049804688
distance losses 0.0 0.0
distributions [0.4131990671157837, 0.08266241103410721, 7.150739520511706e-07]
[{'decision': 0, 'optimal_auc': 0.6375435877566835, 'imitation_auc': 0.6125954198473282, 'optimal_acc': 0.4965986394557823, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9950859950859952, 'imitation_auc': 0.691304347826087, 'optimal_acc': 0.782312925170068, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8140495867768595, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 6 _____
val reward 1.0803581476211548
imitation reward 1.1523510217666626
distance losses 0.0 0.0
distributions [0.879524827003479, 0.3264361321926117, 1.1642753179330612e-06]
[{'decision': 0, 'optimal_auc': 0.6148779542812863, 'imitation_auc': 0.6044847328244275, 'optimal_acc': 0.6122448979591837, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9945945945945945, 'imitation_auc': 0.6929347826086957, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8172282263191354, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 7 _____
val reward 1.069629192352295
imitation reward 1.2011847496032715
distance losses 0.0 0.0
distributions [0.8226965069770813, 0.3855128884315491, 3.314138893983909e-06]
[{'decision': 0, 'optimal_auc': 0.6439364587369236, 'imitation_auc': 0.5896946564885497, 'optimal_acc': 0.6122448979591837, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9943488943488944, 'imitation_auc': 0.6926630434782609, 'optimal_acc': 0.8775510204081632, 'imitation_acc': 0.7278911564625851}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8127781309599491, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 8 _____
val reward 0.7929170727729797
imitation reward 1.2116402387619019
distance losses 0.0 0.0
distributions [0.6298742294311523, 0.3374446630477905, 5.8896707741951104e-06]
[{'decision': 0, 'optimal_auc': 0.6937233630375823, 'imitation_auc': 0.5815839694656488, 'optimal_acc': 0.6326530612244898, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9965601965601966, 'imitation_auc': 0.6942934782608696, 'optimal_acc': 0.9183673469387755, 'imitation_acc': 0.673469387755102}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8207247298156389, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 9 _____
val reward 0.7134961485862732
imitation reward 1.0732219219207764
distance losses 0.0 0.0
distributions [0.5449863076210022, 0.27170529961586, 4.0533282117394265e-06]
[{'decision': 0, 'optimal_auc': 0.7140643161565285, 'imitation_auc': 0.5815839694656488, 'optimal_acc': 0.6598639455782312, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9972972972972973, 'imitation_auc': 0.69375, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8391608391608392, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 10 _____
val reward 0.714495837688446
imitation reward 1.1810708045959473
distance losses 0.0 0.0
distributions [0.6053333878517151, 0.21683740615844727, 1.8536784409661777e-06]
[{'decision': 0, 'optimal_auc': 0.7148392096086789, 'imitation_auc': 0.58206106870229, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9970515970515971, 'imitation_auc': 0.6929347826086957, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8458359821996184, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 11 _____
val reward 0.7022674679756165
imitation reward 1.2857108116149902
distance losses 0.0 0.0
distributions [0.6320682168006897, 0.24061548709869385, 1.4160070804791758e-06]
[{'decision': 0, 'optimal_auc': 0.719876017047656, 'imitation_auc': 0.5825381679389312, 'optimal_acc': 0.6938775510204082, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.9968058968058968, 'imitation_auc': 0.6883152173913043, 'optimal_acc': 0.9727891156462585, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8464717101080736, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 12 _____
val reward 0.7113414406776428
imitation reward 1.2444305419921875
distance losses 0.0 0.0
distributions [0.6116684079170227, 0.2964005172252655, 1.7848984725787886e-06]
[{'decision': 0, 'optimal_auc': 0.7237504843084076, 'imitation_auc': 0.5787213740458015, 'optimal_acc': 0.7006802721088435, 'imitation_acc': 0.8843537414965986}, {'decision': 1, 'optimal_auc': 0.9970515970515971, 'imitation_auc': 0.6926630434782609, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7891156462585034}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8426573426573427, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 13 _____
val reward 0.7605405449867249
imitation reward 1.2109674215316772
distance losses 0.0 0.0
distributions [0.6190702319145203, 0.32039377093315125, 2.41715565607592e-06]
[{'decision': 0, 'optimal_auc': 0.7169701666020921, 'imitation_auc': 0.5791984732824428, 'optimal_acc': 0.6666666666666666, 'imitation_acc': 0.8639455782312925}, {'decision': 1, 'optimal_auc': 0.9972972972972973, 'imitation_auc': 0.6910326086956522, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8372536554354736, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 14 _____
val reward 0.7979321479797363
imitation reward 1.1750988960266113
distance losses 0.0 0.0
distributions [0.6710318922996521, 0.3111531138420105, 3.117663254670333e-06]
[{'decision': 0, 'optimal_auc': 0.696241766757071, 'imitation_auc': 0.5729961832061069, 'optimal_acc': 0.6462585034013606, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9972972972972973, 'imitation_auc': 0.6888586956521738, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8388429752066116, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 15 _____
val reward 0.8132466673851013
imitation reward 1.161198377609253
distance losses 0.0 0.0
distributions [0.7040612101554871, 0.2935412526130676, 3.113297225354472e-06]
[{'decision': 0, 'optimal_auc': 0.6906237892289809, 'imitation_auc': 0.5672709923664122, 'optimal_acc': 0.6530612244897959, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9955773955773957, 'imitation_auc': 0.6866847826086957, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8442466624284806, 'optimal_acc': 1.0, 'imitation_acc': 0.8299319727891157}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 16 _____
val reward 0.7766740918159485
imitation reward 1.1652536392211914
distance losses 0.0 0.0
distributions [0.6727835536003113, 0.2819080352783203, 2.6047507617477095e-06]
[{'decision': 0, 'optimal_auc': 0.7068965517241379, 'imitation_auc': 0.5577290076335877, 'optimal_acc': 0.6326530612244898, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9953316953316953, 'imitation_auc': 0.683695652173913, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8401144310235219, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 17 _____
val reward 0.7517027854919434
imitation reward 1.1965795755386353
distance losses 0.0 0.0
distributions [0.6005849838256836, 0.2779693305492401, 1.900505822050036e-06]
[{'decision': 0, 'optimal_auc': 0.7256877179387834, 'imitation_auc': 0.5510496183206106, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8979591836734694}, {'decision': 1, 'optimal_auc': 0.9950859950859952, 'imitation_auc': 0.6809782608695651, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8258105530832804, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 18 _____
val reward 0.7577696442604065
imitation reward 1.254535436630249
distance losses 0.0 0.0
distributions [0.5767086148262024, 0.2737325429916382, 1.479861111874925e-06]
[{'decision': 0, 'optimal_auc': 0.7282061216582719, 'imitation_auc': 0.5415076335877862, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.891156462585034}, {'decision': 1, 'optimal_auc': 0.994103194103194, 'imitation_auc': 0.6790760869565218, 'optimal_acc': 0.9523809523809523, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.817546090273363, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 19 _____
val reward 0.7695510387420654
imitation reward 1.2992175817489624
distance losses 0.0 0.0
distributions [0.622994065284729, 0.284511923789978, 1.5154067796174786e-06]
[{'decision': 0, 'optimal_auc': 0.7345989926385121, 'imitation_auc': 0.5357824427480916, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8979591836734694}, {'decision': 1, 'optimal_auc': 0.9941031941031941, 'imitation_auc': 0.6790760869565218, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8118245390972664, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 20 _____
val reward 0.7996212840080261
imitation reward 1.3069097995758057
distance losses 0.0 0.0
distributions [0.6754955649375916, 0.2959894835948944, 1.9716628685273463e-06]
[{'decision': 0, 'optimal_auc': 0.7359550561797752, 'imitation_auc': 0.5391221374045801, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8979591836734694}, {'decision': 1, 'optimal_auc': 0.9945945945945945, 'imitation_auc': 0.6804347826086956, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8102352193261284, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 21 _____
val reward 0.8287646770477295
imitation reward 1.3061859607696533
distance losses 0.0 0.0
distributions [0.6877720952033997, 0.30453646183013916, 2.4581663637945894e-06]
[{'decision': 0, 'optimal_auc': 0.7380860131731887, 'imitation_auc': 0.5333969465648855, 'optimal_acc': 0.6938775510204082, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9941031941031941, 'imitation_auc': 0.6883152173913043, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8045136681500318, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 22 _____
val reward 0.8296757340431213
imitation reward 1.3188128471374512
distance losses 0.0 0.0
distributions [0.6608731150627136, 0.3049556612968445, 2.761638825177215e-06]
[{'decision': 0, 'optimal_auc': 0.7400232468035645, 'imitation_auc': 0.5343511450381679, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9931203931203931, 'imitation_auc': 0.692391304347826, 'optimal_acc': 0.9183673469387755, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7987921169739352, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 23 _____
val reward 0.8260146975517273
imitation reward 1.337039828300476
distance losses 0.0 0.0
distributions [0.6252221465110779, 0.2962227165699005, 2.600504558358807e-06]
[{'decision': 0, 'optimal_auc': 0.7411855869817899, 'imitation_auc': 0.536736641221374, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9921375921375921, 'imitation_auc': 0.6994565217391304, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7210884353741497}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7914812460267007, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 24 _____
val reward 0.8343362212181091
imitation reward 1.3524993658065796
distance losses 0.0 0.0
distributions [0.6013851165771484, 0.2837950587272644, 2.033489408859168e-06]
[{'decision': 0, 'optimal_auc': 0.7386671832623015, 'imitation_auc': 0.5472328244274809, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9911547911547911, 'imitation_auc': 0.7027173913043478, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7278911564625851}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7806738715829625, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 25 _____
val reward 0.8530329465866089
imitation reward 1.3869866132736206
distance losses 0.0 0.0
distributions [0.6113686561584473, 0.27252790331840515, 1.451257617191004e-06]
[{'decision': 0, 'optimal_auc': 0.7400232468035646, 'imitation_auc': 0.5510496183206106, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.9894348894348894, 'imitation_auc': 0.7029891304347826, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7784488239033693, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 26 _____
val reward 0.893599808216095
imitation reward 1.4554766416549683
distance losses 0.0 0.0
distributions [0.6295285224914551, 0.28703969717025757, 1.151088781625731e-06]
[{'decision': 0, 'optimal_auc': 0.7380860131731887, 'imitation_auc': 0.549618320610687, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8707482993197279}, {'decision': 1, 'optimal_auc': 0.9906633906633907, 'imitation_auc': 0.6994565217391304, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7781309599491417, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 27 _____
val reward 0.9487404227256775
imitation reward 1.509016752243042
distance losses 0.0 0.0
distributions [0.6279917359352112, 0.3062254786491394, 1.1648319286905462e-06]
[{'decision': 0, 'optimal_auc': 0.7415730337078652, 'imitation_auc': 0.545324427480916, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8571428571428571}, {'decision': 1, 'optimal_auc': 0.990909090909091, 'imitation_auc': 0.6929347826086956, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7768595041322314, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 28 _____
val reward 1.0042864084243774
imitation reward 1.538038730621338
distance losses 0.0 0.0
distributions [0.6143869757652283, 0.314139187335968, 1.2826579904867685e-06]
[{'decision': 0, 'optimal_auc': 0.738860906625339, 'imitation_auc': 0.5391221374045801, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.990909090909091, 'imitation_auc': 0.6951086956521739, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7730451366815003, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 29 _____
val reward 1.0231831073760986
imitation reward 1.5473542213439941
distance losses 0.0 0.0
distributions [0.619814395904541, 0.3049829304218292, 1.495580477239855e-06]
[{'decision': 0, 'optimal_auc': 0.7363425029058505, 'imitation_auc': 0.5388835877862596, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9901719901719902, 'imitation_auc': 0.6940217391304347, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7676414494596313, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 30 _____
val reward 1.0318124294281006
imitation reward 1.5734739303588867
distance losses 0.0 0.0
distributions [0.633472204208374, 0.28821370005607605, 1.4448114598053508e-06]
[{'decision': 0, 'optimal_auc': 0.736536226268888, 'imitation_auc': 0.5419847328244275, 'optimal_acc': 0.6666666666666666, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9894348894348894, 'imitation_auc': 0.6923913043478261, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7606484424666243, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 31 _____
val reward 1.0451717376708984
imitation reward 1.6208304166793823
distance losses 0.0 0.0
distributions [0.6109630465507507, 0.2793640196323395, 1.2028986020595767e-06]
[{'decision': 0, 'optimal_auc': 0.7371173963580008, 'imitation_auc': 0.5534351145038168, 'optimal_acc': 0.6598639455782312, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9886977886977887, 'imitation_auc': 0.6853260869565216, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7571519389701208, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 32 _____
val reward 1.066649317741394
imitation reward 1.6636414527893066
distance losses 0.0 0.0
distributions [0.588704526424408, 0.2912026345729828, 9.314181852460024e-07]
[{'decision': 0, 'optimal_auc': 0.7404106935296397, 'imitation_auc': 0.5586832061068703, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9896805896805897, 'imitation_auc': 0.6769021739130435, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7565162110616657, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 33 _____
val reward 1.1084867715835571
imitation reward 1.7311301231384277
distance losses 0.0 0.0
distributions [0.5941031575202942, 0.3038376271724701, 7.003191626608896e-07]
[{'decision': 0, 'optimal_auc': 0.7431228206121658, 'imitation_auc': 0.5639312977099237, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9904176904176905, 'imitation_auc': 0.6616847826086957, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7581055308328036, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 34 _____
val reward 1.1377475261688232
imitation reward 1.795758843421936
distance losses 0.0 0.0
distributions [0.5969951748847961, 0.30733874440193176, 5.615084432974982e-07]
[{'decision': 0, 'optimal_auc': 0.7454475009686168, 'imitation_auc': 0.5639312977099237, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.990909090909091, 'imitation_auc': 0.6448369565217391, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7527018436109346, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 35 _____
val reward 1.1270570755004883
imitation reward 1.825864553451538
distance losses 0.0 0.0
distributions [0.6015615463256836, 0.30127769708633423, 5.387012720348139e-07]
[{'decision': 0, 'optimal_auc': 0.7537776055792329, 'imitation_auc': 0.5677480916030534, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9889434889434889, 'imitation_auc': 0.6391304347826087, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7504767959313414, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 36 _____
val reward 1.1099187135696411
imitation reward 1.8633837699890137
distance losses 0.0 0.0
distributions [0.5807569026947021, 0.2906993329524994, 5.261244950816035e-07]
[{'decision': 0, 'optimal_auc': 0.761139093374661, 'imitation_auc': 0.5653625954198473, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9886977886977887, 'imitation_auc': 0.6415760869565218, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7415766052129689, 'optimal_acc': 1.0, 'imitation_acc': 0.7687074829931972}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 37 _____
val reward 1.124311089515686
imitation reward 1.9185787439346313
distance losses 0.0 0.0
distributions [0.5477613806724548, 0.28367000818252563, 4.5184305008660886e-07]
[{'decision': 0, 'optimal_auc': 0.7677256877179388, 'imitation_auc': 0.5682251908396946, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9872235872235873, 'imitation_auc': 0.6451086956521739, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7294977749523204, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 38 _____
val reward 1.1226226091384888
imitation reward 1.9880397319793701
distance losses 0.0 0.0
distributions [0.5775079131126404, 0.2831230163574219, 3.595327484617883e-07]
[{'decision': 0, 'optimal_auc': 0.7690817512592019, 'imitation_auc': 0.5677480916030534, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9872235872235873, 'imitation_auc': 0.6440217391304348, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7177368086458995, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 39 _____
val reward 1.1484229564666748
imitation reward 2.0849130153656006
distance losses 0.0 0.0
distributions [0.6437362432479858, 0.2862473428249359, 2.621891894705186e-07]
[{'decision': 0, 'optimal_auc': 0.7692754746222394, 'imitation_auc': 0.5696564885496184, 'optimal_acc': 0.7074829931972789, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9874692874692875, 'imitation_auc': 0.6331521739130435, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7066115702479339, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 40 _____
val reward 1.1743073463439941
imitation reward 2.1874125003814697
distance losses 0.0 0.0
distributions [0.6391404867172241, 0.2902525067329407, 2.3822168770948338e-07]
[{'decision': 0, 'optimal_auc': 0.7739248353351414, 'imitation_auc': 0.5715648854961832, 'optimal_acc': 0.7142857142857143, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9886977886977888, 'imitation_auc': 0.6323369565217392, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7012078830260648, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 41 _____
val reward 1.2074487209320068
imitation reward 2.2887535095214844
distance losses 0.0 0.0
distributions [0.5979651212692261, 0.29607245326042175, 2.4904227302613435e-07]
[{'decision': 0, 'optimal_auc': 0.7710189848895778, 'imitation_auc': 0.5687022900763359, 'optimal_acc': 0.7074829931972789, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9882063882063883, 'imitation_auc': 0.6353260869565218, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6945327399872855, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 42 _____
val reward 1.2599964141845703
imitation reward 2.36313533782959
distance losses 0.0 0.0
distributions [0.5638958215713501, 0.29710298776626587, 2.736709632245038e-07]
[{'decision': 0, 'optimal_auc': 0.762495156915924, 'imitation_auc': 0.5634541984732825, 'optimal_acc': 0.6938775510204082, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9877149877149878, 'imitation_auc': 0.6445652173913043, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6853146853146853, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 43 _____
val reward 1.2681187391281128
imitation reward 2.385983943939209
distance losses 0.0 0.0
distributions [0.5952240824699402, 0.29238778352737427, 3.109297210812656e-07]
[{'decision': 0, 'optimal_auc': 0.7522278186749322, 'imitation_auc': 0.5625, 'optimal_acc': 0.7142857142857143, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9874692874692874, 'imitation_auc': 0.6461956521739131, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6907183725365543, 'optimal_acc': 1.0, 'imitation_acc': 0.7482993197278912}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 44 _____
val reward 1.297957181930542
imitation reward 2.396855115890503
distance losses 0.0 0.0
distributions [0.6168555617332458, 0.28374215960502625, 2.8139797336734773e-07]
[{'decision': 0, 'optimal_auc': 0.7409918636187526, 'imitation_auc': 0.5648854961832062, 'optimal_acc': 0.7074829931972789, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.986977886977887, 'imitation_auc': 0.6461956521739131, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.685632549268913, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 45 _____
val reward 1.3238863945007324
imitation reward 2.4185495376586914
distance losses 0.0 0.0
distributions [0.6213146448135376, 0.27983856201171875, 2.450472607051779e-07]
[{'decision': 0, 'optimal_auc': 0.7363425029058506, 'imitation_auc': 0.5605916030534351, 'optimal_acc': 0.7210884353741497, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9867321867321868, 'imitation_auc': 0.6369565217391304, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.691036236490782, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 46 _____
val reward 1.3354825973510742
imitation reward 2.4321751594543457
distance losses 0.0 0.0
distributions [0.5979888439178467, 0.2881177067756653, 2.590813323877228e-07]
[{'decision': 0, 'optimal_auc': 0.7427353738860906, 'imitation_auc': 0.560114503816794, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9889434889434889, 'imitation_auc': 0.6296195652173913, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7015257469802925, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 47 _____
val reward 1.3667258024215698
imitation reward 2.4159388542175293
distance losses 0.0 0.0
distributions [0.6034138202667236, 0.29928287863731384, 2.6460156732355244e-07]
[{'decision': 0, 'optimal_auc': 0.7417667570709028, 'imitation_auc': 0.5548664122137404, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.7959183673469388}, {'decision': 1, 'optimal_auc': 0.9896805896805898, 'imitation_auc': 0.626358695652174, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7005721551176096, 'optimal_acc': 1.0, 'imitation_acc': 0.7551020408163265}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 48 _____
val reward 1.35378098487854
imitation reward 2.4015066623687744
distance losses 0.0 0.0
distributions [0.6143922209739685, 0.2978466749191284, 2.5408365900148056e-07]
[{'decision': 0, 'optimal_auc': 0.7427353738860906, 'imitation_auc': 0.5567748091603053, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.98992628992629, 'imitation_auc': 0.6331521739130435, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.705022250476796, 'optimal_acc': 1.0, 'imitation_acc': 0.7346938775510204}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 49 _____
val reward 1.3487601280212402
imitation reward 2.382091999053955
distance losses 0.0 0.0
distributions [0.6239352822303772, 0.29763975739479065, 2.2485075135136867e-07]
[{'decision': 0, 'optimal_auc': 0.7446726075164666, 'imitation_auc': 0.5558206106870229, 'optimal_acc': 0.6666666666666666, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.9914004914004914, 'imitation_auc': 0.6429347826086957, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7053401144310235, 'optimal_acc': 1.0, 'imitation_acc': 0.7551020408163265}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 50 _____
val reward 1.3374929428100586
imitation reward 2.3527493476867676
distance losses 0.0 0.0
distributions [0.6145166158676147, 0.29649636149406433, 2.2654572262581496e-07]
[{'decision': 0, 'optimal_auc': 0.7479659046881054, 'imitation_auc': 0.5648854961832062, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.9916461916461917, 'imitation_auc': 0.6611413043478261, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7018436109345201, 'optimal_acc': 1.0, 'imitation_acc': 0.7551020408163265}]

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 51 _____
val reward 1.305857539176941
imitation reward 2.368690013885498
distance losses 0.0 0.0
distributions [0.6201431155204773, 0.2831052243709564, 1.94479909509937e-07]
[{'decision': 0, 'optimal_auc': 0.7512592018597444, 'imitation_auc': 0.5620229007633588, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.990909090909091, 'imitation_auc': 0.6711956521739131, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6951684678957406, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 52 _____
val reward 1.2856413125991821
imitation reward 2.4572396278381348
distance losses 0.0 0.0
distributions [0.576102614402771, 0.2761238217353821, 1.7593909262814122e-07]
[{'decision': 0, 'optimal_auc': 0.7584269662921348, 'imitation_auc': 0.5543893129770993, 'optimal_acc': 0.7006802721088435, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9906633906633907, 'imitation_auc': 0.6752717391304347, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6973935155753338, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 53 _____
val reward 1.2507784366607666
imitation reward 2.5304839611053467
distance losses 0.0 0.0
distributions [0.5734046697616577, 0.2723652720451355, 1.7794401685478078e-07]
[{'decision': 0, 'optimal_auc': 0.7644323905462999, 'imitation_auc': 0.5500954198473282, 'optimal_acc': 0.7006802721088435, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9904176904176905, 'imitation_auc': 0.6763586956521739, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6951684678957406, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 54 _____
val reward 1.2419277429580688
imitation reward 2.5390079021453857
distance losses 0.0 0.0
distributions [0.6029841899871826, 0.2776681184768677, 2.538087926495791e-07]
[{'decision': 0, 'optimal_auc': 0.7661759008136381, 'imitation_auc': 0.5458015267175572, 'optimal_acc': 0.7074829931972789, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9918918918918919, 'imitation_auc': 0.6796195652173913, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6900826446280992, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 55 _____
val reward 1.2573517560958862
imitation reward 2.5233521461486816
distance losses 0.0 0.0
distributions [0.6183192729949951, 0.28608065843582153, 3.4504833479331865e-07]
[{'decision': 0, 'optimal_auc': 0.7655947307245253, 'imitation_auc': 0.5458015267175572, 'optimal_acc': 0.6938775510204082, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9931203931203931, 'imitation_auc': 0.685054347826087, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6888111888111889, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 56 _____
val reward 1.2775623798370361
imitation reward 2.5254600048065186
distance losses 0.0 0.0
distributions [0.594770073890686, 0.2983497977256775, 4.769042334373808e-07]
[{'decision': 0, 'optimal_auc': 0.7708252615265401, 'imitation_auc': 0.5434160305343512, 'optimal_acc': 0.6938775510204082, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9928746928746929, 'imitation_auc': 0.6921195652173914, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6932612841703751, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 57 _____
val reward 1.3048264980316162
imitation reward 2.5322484970092773
distance losses 0.0 0.0
distributions [0.5829581022262573, 0.30130234360694885, 4.908910113954335e-07]
[{'decision': 0, 'optimal_auc': 0.7760557923285549, 'imitation_auc': 0.5493797709923665, 'optimal_acc': 0.7074829931972789, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9928746928746929, 'imitation_auc': 0.6942934782608697, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6977113795295613, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 58 _____
val reward 1.330456018447876
imitation reward 2.5390892028808594
distance losses 0.0 0.0
distributions [0.5921155214309692, 0.30127373337745667, 4.5681611027248437e-07]
[{'decision': 0, 'optimal_auc': 0.7675319643549012, 'imitation_auc': 0.5562977099236641, 'optimal_acc': 0.7074829931972789, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9926289926289926, 'imitation_auc': 0.6899456521739131, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6983471074380165, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 59 _____
val reward 1.3535157442092896
imitation reward 2.5425634384155273
distance losses 0.0 0.0
distributions [0.5999701619148254, 0.2982739210128784, 4.202176455692097e-07]
[{'decision': 0, 'optimal_auc': 0.7576520728399846, 'imitation_auc': 0.5658396946564885, 'optimal_acc': 0.7006802721088435, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9918918918918919, 'imitation_auc': 0.6877717391304348, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7005721551176096, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 60 _____
val reward 1.3877686262130737
imitation reward 2.564135789871216
distance losses 0.0 0.0
distributions [0.6169390678405762, 0.29263174533843994, 3.9519466099591227e-07]
[{'decision': 0, 'optimal_auc': 0.7419604804339404, 'imitation_auc': 0.571087786259542, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9906633906633907, 'imitation_auc': 0.6885869565217391, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7012078830260648, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 61 _____
val reward 1.4483392238616943
imitation reward 2.6097118854522705
distance losses 0.0 0.0
distributions [0.634914755821228, 0.28156596422195435, 3.499964691400237e-07]
[{'decision': 0, 'optimal_auc': 0.728690430065866, 'imitation_auc': 0.5768129770992367, 'optimal_acc': 0.6666666666666666, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9889434889434889, 'imitation_auc': 0.6809782608695654, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6999364272091545, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 62 _____
val reward 1.4913341999053955
imitation reward 2.652698040008545
distance losses 0.0 0.0
distributions [0.6341712474822998, 0.27886199951171875, 3.707408211539587e-07]
[{'decision': 0, 'optimal_auc': 0.7145486245641225, 'imitation_auc': 0.5787213740458016, 'optimal_acc': 0.6666666666666666, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9877149877149877, 'imitation_auc': 0.675, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6986649713922441, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 63 _____
val reward 1.4883979558944702
imitation reward 2.7327513694763184
distance losses 0.0 0.0
distributions [0.603850781917572, 0.2844223380088806, 4.1530537941980583e-07]
[{'decision': 0, 'optimal_auc': 0.7115459124370399, 'imitation_auc': 0.5844465648854962, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9869778869778869, 'imitation_auc': 0.6682065217391304, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7043865225683408, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 64 _____
val reward 1.494387149810791
imitation reward 2.7553038597106934
distance losses 0.0 0.0
distributions [0.5729195475578308, 0.2981221079826355, 5.460863121697912e-07]
[{'decision': 0, 'optimal_auc': 0.7171638899651298, 'imitation_auc': 0.5911259541984732, 'optimal_acc': 0.6666666666666666, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9877149877149878, 'imitation_auc': 0.6630434782608695, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.708836617927527, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 65 _____
val reward 1.5008846521377563
imitation reward 2.7834672927856445
distance losses 0.0 0.0
distributions [0.5600261688232422, 0.30641788244247437, 6.280835691541142e-07]
[{'decision': 0, 'optimal_auc': 0.725881441301821, 'imitation_auc': 0.5947041984732824, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9874692874692875, 'imitation_auc': 0.6567934782608695, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7139224411951685, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 66 _____
val reward 1.4786782264709473
imitation reward 2.7797341346740723
distance losses 0.0 0.0
distributions [0.5968485474586487, 0.30434098839759827, 5.826902906846954e-07]
[{'decision': 0, 'optimal_auc': 0.7256877179387834, 'imitation_auc': 0.5963740458015268, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9864864864864865, 'imitation_auc': 0.647554347826087, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.782312925170068}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7088366179275271, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 67 _____
val reward 1.4890090227127075
imitation reward 2.79229736328125
distance losses 0.0 0.0
distributions [0.650434136390686, 0.295519083738327, 3.7626040239047143e-07]
[{'decision': 0, 'optimal_auc': 0.7222006974041069, 'imitation_auc': 0.5978053435114504, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.985012285012285, 'imitation_auc': 0.6410326086956522, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7005721551176096, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 68 _____
val reward 1.4992179870605469
imitation reward 2.7952194213867188
distance losses 0.0 0.0
distributions [0.661888599395752, 0.2901016175746918, 2.6344400794187095e-07]
[{'decision': 0, 'optimal_auc': 0.724525377760558, 'imitation_auc': 0.6006679389312977, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.984029484029484, 'imitation_auc': 0.6375, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6945327399872854, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 69 _____
val reward 1.4924286603927612
imitation reward 2.826500415802002
distance losses 0.0 0.0
distributions [0.6389517784118652, 0.2888942360877991, 2.081009995436034e-07]
[{'decision': 0, 'optimal_auc': 0.725881441301821, 'imitation_auc': 0.5997137404580153, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9828009828009827, 'imitation_auc': 0.6355978260869565, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6929434202161475, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 70 _____
val reward 1.490447759628296
imitation reward 2.863691568374634
distance losses 0.0 0.0
distributions [0.5867536067962646, 0.29015493392944336, 1.5069959147240297e-07]
[{'decision': 0, 'optimal_auc': 0.7311119721038357, 'imitation_auc': 0.5961354961832062, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9820638820638821, 'imitation_auc': 0.6347826086956522, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6996185632549269, 'optimal_acc': 1.0, 'imitation_acc': 0.8095238095238095}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 71 _____
val reward 1.5002907514572144
imitation reward 2.8600502014160156
distance losses 0.0 0.0
distributions [0.574472188949585, 0.29489707946777344, 1.5512087259139662e-07]
[{'decision': 0, 'optimal_auc': 0.7334366524602868, 'imitation_auc': 0.5925572519083969, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9832923832923833, 'imitation_auc': 0.6279891304347827, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7053401144310235, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 72 _____
val reward 1.4940941333770752
imitation reward 2.851438522338867
distance losses 0.0 0.0
distributions [0.5957499146461487, 0.3009837865829468, 1.6911319278278825e-07]
[{'decision': 0, 'optimal_auc': 0.7390546299883766, 'imitation_auc': 0.5820610687022901, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9869778869778869, 'imitation_auc': 0.6241847826086956, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7113795295613478, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 73 _____
val reward 1.5113810300827026
imitation reward 2.831815719604492
distance losses 0.0 0.0
distributions [0.6201545000076294, 0.30636799335479736, 1.8984290761636657e-07]
[{'decision': 0, 'optimal_auc': 0.7386671832623014, 'imitation_auc': 0.5811068702290076, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9886977886977887, 'imitation_auc': 0.6252717391304348, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7113795295613479, 'optimal_acc': 1.0, 'imitation_acc': 0.8027210884353742}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 74 _____
val reward 1.536510705947876
imitation reward 2.838913917541504
distance losses 0.0 0.0
distributions [0.6386047005653381, 0.30711010098457336, 1.895736119195135e-07]
[{'decision': 0, 'optimal_auc': 0.7369236729949632, 'imitation_auc': 0.5782442748091603, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.98992628992629, 'imitation_auc': 0.6342391304347826, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7082008900190719, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 75 _____
val reward 1.5381505489349365
imitation reward 2.865497589111328
distance losses 0.0 0.0
distributions [0.6328425407409668, 0.3005111515522003, 2.379083667847226e-07]
[{'decision': 0, 'optimal_auc': 0.7415730337078652, 'imitation_auc': 0.5777671755725191, 'optimal_acc': 0.7006802721088435, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9891891891891892, 'imitation_auc': 0.6489130434782608, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.705022250476796, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 76 _____
val reward 1.5160620212554932
imitation reward 2.9294488430023193
distance losses 0.0 0.0
distributions [0.6152823567390442, 0.29463738203048706, 2.769369871202798e-07]
[{'decision': 0, 'optimal_auc': 0.743510267338241, 'imitation_auc': 0.5706106870229009, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9862407862407863, 'imitation_auc': 0.6529891304347826, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7040686586141132, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 77 _____
val reward 1.508471965789795
imitation reward 2.945549964904785
distance losses 0.0 0.0
distributions [0.5845640897750854, 0.2892393469810486, 3.623805184815865e-07]
[{'decision': 0, 'optimal_auc': 0.744866330879504, 'imitation_auc': 0.560114503816794, 'optimal_acc': 0.6598639455782312, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9842751842751842, 'imitation_auc': 0.6660326086956522, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7069294342021615, 'optimal_acc': 1.0, 'imitation_acc': 0.7959183673469388}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 78 _____
val reward 1.5010889768600464
imitation reward 2.9540324211120605
distance losses 0.0 0.0
distributions [0.5744267702102661, 0.2842182219028473, 3.3818420774878177e-07]
[{'decision': 0, 'optimal_auc': 0.7446726075164665, 'imitation_auc': 0.5515267175572519, 'optimal_acc': 0.6666666666666666, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9835380835380835, 'imitation_auc': 0.6752717391304349, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7110616656071201, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 79 _____
val reward 1.506151795387268
imitation reward 2.9905102252960205
distance losses 0.0 0.0
distributions [0.5788644552230835, 0.28084099292755127, 3.304779170321126e-07]
[{'decision': 0, 'optimal_auc': 0.7420573421154592, 'imitation_auc': 0.5467557251908397, 'optimal_acc': 0.6530612244897959, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.984029484029484, 'imitation_auc': 0.6687500000000001, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7113795295613478, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 80 _____
val reward 1.4862903356552124
imitation reward 3.0532712936401367
distance losses 0.0 0.0
distributions [0.5813463926315308, 0.28434139490127563, 3.724200325905258e-07]
[{'decision': 0, 'optimal_auc': 0.7378922898101511, 'imitation_auc': 0.5448473282442748, 'optimal_acc': 0.6530612244897959, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.985012285012285, 'imitation_auc': 0.6641304347826087, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7755102040816326}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7116973935155753, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 81 _____
val reward 1.4605624675750732
imitation reward 3.097799777984619
distance losses 0.0 0.0
distributions [0.5926443338394165, 0.29205119609832764, 4.704613445483119e-07]
[{'decision': 0, 'optimal_auc': 0.7388609066253391, 'imitation_auc': 0.5467557251908397, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.985995085995086, 'imitation_auc': 0.6578804347826086, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7069294342021615, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 82 _____
val reward 1.451874852180481
imitation reward 3.051133155822754
distance losses 0.0 0.0
distributions [0.6019473671913147, 0.3000366687774658, 6.316602139122551e-07]
[{'decision': 0, 'optimal_auc': 0.7367299496319256, 'imitation_auc': 0.5534351145038168, 'optimal_acc': 0.6938775510204082, 'imitation_acc': 0.7959183673469388}, {'decision': 1, 'optimal_auc': 0.986977886977887, 'imitation_auc': 0.6557065217391304, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.7015257469802925, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 83 _____
val reward 1.460404872894287
imitation reward 3.0167064666748047
distance losses 0.0 0.0
distributions [0.6024476885795593, 0.30746859312057495, 7.44055398627097e-07]
[{'decision': 0, 'optimal_auc': 0.7365362262688879, 'imitation_auc': 0.5579675572519084, 'optimal_acc': 0.7006802721088435, 'imitation_acc': 0.7891156462585034}, {'decision': 1, 'optimal_auc': 0.9877149877149878, 'imitation_auc': 0.651358695652174, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6973935155753338, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 84 _____
val reward 1.4860831499099731
imitation reward 3.0189270973205566
distance losses 0.0 0.0
distributions [0.5917388796806335, 0.3103603422641754, 8.84583130300598e-07]
[{'decision': 0, 'optimal_auc': 0.7369236729949632, 'imitation_auc': 0.5605916030534351, 'optimal_acc': 0.7210884353741497, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9877149877149878, 'imitation_auc': 0.6475543478260869, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6865861411315957, 'optimal_acc': 1.0, 'imitation_acc': 0.782312925170068}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 85 _____
val reward 1.507522702217102
imitation reward 3.0429062843322754
distance losses 0.0 0.0
distributions [0.5773240923881531, 0.3034202456474304, 1.1013844414264895e-06]
[{'decision': 0, 'optimal_auc': 0.7353738860906626, 'imitation_auc': 0.5656011450381679, 'optimal_acc': 0.7074829931972789, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9867321867321868, 'imitation_auc': 0.6353260869565218, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6818181818181818, 'optimal_acc': 1.0, 'imitation_acc': 0.7891156462585034}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 86 _____
val reward 1.5338114500045776
imitation reward 3.0657691955566406
distance losses 0.0 0.0
distributions [0.5807653665542603, 0.2933906614780426, 1.4497611573460745e-06]
[{'decision': 0, 'optimal_auc': 0.7347927160015498, 'imitation_auc': 0.572280534351145, 'optimal_acc': 0.7074829931972789, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9842751842751842, 'imitation_auc': 0.6347826086956522, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6780038143674507, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 87 _____
val reward 1.5686683654785156
imitation reward 3.137742042541504
distance losses 0.0 0.0
distributions [0.6077306270599365, 0.2819221019744873, 1.5174726968325558e-06]
[{'decision': 0, 'optimal_auc': 0.725881441301821, 'imitation_auc': 0.5832538167938931, 'optimal_acc': 0.7006802721088435, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9835380835380836, 'imitation_auc': 0.6323369565217392, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6710108073744437, 'optimal_acc': 1.0, 'imitation_acc': 0.7482993197278912}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 88 _____
val reward 1.620465636253357
imitation reward 3.2027993202209473
distance losses 0.0 0.0
distributions [0.629379391670227, 0.2838924825191498, 1.3655858310812619e-06]
[{'decision': 0, 'optimal_auc': 0.725009686168152, 'imitation_auc': 0.5803912213740459, 'optimal_acc': 0.6870748299319728, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9825552825552826, 'imitation_auc': 0.627445652173913, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6719643992371266, 'optimal_acc': 1.0, 'imitation_acc': 0.7414965986394558}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 89 _____
val reward 1.6777215003967285
imitation reward 3.1982059478759766
distance losses 0.0 0.0
distributions [0.6440876722335815, 0.2932434380054474, 1.238620029653248e-06]
[{'decision': 0, 'optimal_auc': 0.7237504843084076, 'imitation_auc': 0.5837309160305344, 'optimal_acc': 0.6666666666666666, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.983046683046683, 'imitation_auc': 0.6320652173913043, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7687074829931972}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6805467260012714, 'optimal_acc': 1.0, 'imitation_acc': 0.7346938775510204}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 90 _____
val reward 1.7266262769699097
imitation reward 3.1848230361938477
distance losses 0.0 0.0
distributions [0.6495662927627563, 0.30050531029701233, 1.0105362662216066e-06]
[{'decision': 0, 'optimal_auc': 0.7194885703215808, 'imitation_auc': 0.5854007633587786, 'optimal_acc': 0.6666666666666666, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.9840294840294841, 'imitation_auc': 0.6432065217391305, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6805467260012714, 'optimal_acc': 1.0, 'imitation_acc': 0.7482993197278912}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 91 _____
val reward 1.7440637350082397
imitation reward 3.188775062561035
distance losses 0.0 0.0
distributions [0.6362856030464172, 0.3036397695541382, 7.264965233844123e-07]
[{'decision': 0, 'optimal_auc': 0.718907400232468, 'imitation_auc': 0.5873091603053435, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.9840294840294841, 'imitation_auc': 0.6472826086956521, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.684043229497775, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 92 _____
val reward 1.7522724866867065
imitation reward 3.1909894943237305
distance losses 0.0 0.0
distributions [0.6093952655792236, 0.29928886890411377, 5.752314109486178e-07]
[{'decision': 0, 'optimal_auc': 0.7173576133281673, 'imitation_auc': 0.5951812977099237, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9815724815724816, 'imitation_auc': 0.652445652173913, 'optimal_acc': 0.9319727891156463, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6872218690400508, 'optimal_acc': 1.0, 'imitation_acc': 0.7755102040816326}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 93 _____
val reward 1.7560621500015259
imitation reward 3.202814817428589
distance losses 0.0 0.0
distributions [0.5781822204589844, 0.2947305738925934, 5.357722443477542e-07]
[{'decision': 0, 'optimal_auc': 0.7231693142192949, 'imitation_auc': 0.607824427480916, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9803439803439804, 'imitation_auc': 0.6559782608695652, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6872218690400509, 'optimal_acc': 1.0, 'imitation_acc': 0.7687074829931972}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 94 _____
val reward 1.7659416198730469
imitation reward 3.203749656677246
distance losses 0.0 0.0
distributions [0.5626543760299683, 0.2941169738769531, 6.060044484001992e-07]
[{'decision': 0, 'optimal_auc': 0.7251065478496707, 'imitation_auc': 0.6106870229007634, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9798525798525799, 'imitation_auc': 0.6619565217391304, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.682453909726637, 'optimal_acc': 1.0, 'imitation_acc': 0.7687074829931972}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 95 _____
val reward 1.7664412260055542
imitation reward 3.115159749984741
distance losses 0.0 0.0
distributions [0.5809111595153809, 0.29408586025238037, 9.245503633792396e-07]
[{'decision': 0, 'optimal_auc': 0.7239442076714452, 'imitation_auc': 0.602337786259542, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9793611793611794, 'imitation_auc': 0.6646739130434782, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6783216783216783, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 96 _____
val reward 1.776654839515686
imitation reward 3.042977809906006
distance losses 0.0 0.0
distributions [0.6067156195640564, 0.2961047291755676, 1.2143099183958839e-06]
[{'decision': 0, 'optimal_auc': 0.72355676094537, 'imitation_auc': 0.5889790076335878, 'optimal_acc': 0.673469387755102, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9786240786240786, 'imitation_auc': 0.6633152173913044, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6735537190082644, 'optimal_acc': 1.0, 'imitation_acc': 0.7551020408163265}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 97 _____
val reward 1.7803577184677124
imitation reward 3.020273447036743
distance losses 0.0 0.0
distributions [0.6313069462776184, 0.2957758605480194, 1.536881768515741e-06]
[{'decision': 0, 'optimal_auc': 0.7198760170476559, 'imitation_auc': 0.5791984732824428, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.9805896805896805, 'imitation_auc': 0.6608695652173913, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6741894469167196, 'optimal_acc': 1.0, 'imitation_acc': 0.7482993197278912}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 98 _____
val reward 1.7654328346252441
imitation reward 3.025085687637329
distance losses 0.0 0.0
distributions [0.6421538591384888, 0.29840099811553955, 1.8816366491591907e-06]
[{'decision': 0, 'optimal_auc': 0.7169701666020922, 'imitation_auc': 0.5701335877862596, 'optimal_acc': 0.6802721088435374, 'imitation_acc': 0.8231292517006803}, {'decision': 1, 'optimal_auc': 0.9830466830466831, 'imitation_auc': 0.658695652173913, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7414965986394558}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.67546090273363, 'optimal_acc': 1.0, 'imitation_acc': 0.7482993197278912}]

tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 99 _____
val reward 1.7269372940063477
imitation reward 3.082510471343994
distance losses 0.0 0.0
distributions [0.6284551620483398, 0.30066436529159546, 1.6690353277226677e-06]
[{'decision': 0, 'optimal_auc': 0.7237504843084076, 'imitation_auc': 0.5634541984732825, 'optimal_acc': 0.6598639455782312, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9842751842751843, 'imitation_auc': 0.6516304347826086, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.677050222504768, 'optimal_acc': 1.0, 'imitation_acc': 0.7687074829931972}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 100 _____
val reward 1.7080286741256714
imitation reward 3.147000312805176
distance losses 0.0 0.0
distributions [0.6168451905250549, 0.30266278982162476, 1.2882969713245984e-06]
[{'decision': 0, 'optimal_auc': 0.7260751646648587, 'imitation_auc': 0.5653625954198473, 'optimal_acc': 0.6530612244897959, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9845208845208846, 'imitation_auc': 0.6467391304347826, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7346938775510204}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6748251748251749, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 101 _____
val reward 1.6782917976379395
imitation reward 3.1914498805999756
distance losses 0.0 0.0
distributions [0.605720043182373, 0.2999368906021118, 9.559324780639145e-07]
[{'decision': 0, 'optimal_auc': 0.7270437814800464, 'imitation_auc': 0.5687022900763359, 'optimal_acc': 0.6530612244897959, 'imitation_acc': 0.7959183673469388}, {'decision': 1, 'optimal_auc': 0.9835380835380835, 'imitation_auc': 0.6464673913043478, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6719643992371265, 'optimal_acc': 1.0, 'imitation_acc': 0.7687074829931972}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 102 _____
val reward 1.6574147939682007
imitation reward 3.1662402153015137
distance losses 0.0 0.0
distributions [0.5939082503318787, 0.2950376272201538, 8.008653935576149e-07]
[{'decision': 0, 'optimal_auc': 0.7289810151104222, 'imitation_auc': 0.5725190839694656, 'optimal_acc': 0.6530612244897959, 'imitation_acc': 0.7891156462585034}, {'decision': 1, 'optimal_auc': 0.983046683046683, 'imitation_auc': 0.6527173913043478, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6691036236490782, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 103 _____
val reward 1.641277551651001
imitation reward 3.124229669570923
distance losses 0.0 0.0
distributions [0.6009122133255005, 0.2866540253162384, 7.327597018047527e-07]
[{'decision': 0, 'optimal_auc': 0.7274312282061216, 'imitation_auc': 0.5744274809160306, 'optimal_acc': 0.6598639455782312, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.9825552825552826, 'imitation_auc': 0.6535326086956521, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6611570247933884, 'optimal_acc': 1.0, 'imitation_acc': 0.7551020408163265}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 104 _____
val reward 1.6442421674728394
imitation reward 3.12288498878479
distance losses 0.0 0.0
distributions [0.6065036654472351, 0.28019222617149353, 6.937302146070579e-07]
[{'decision': 0, 'optimal_auc': 0.7218132506780318, 'imitation_auc': 0.5782442748091603, 'optimal_acc': 0.6598639455782312, 'imitation_acc': 0.8027210884353742}, {'decision': 1, 'optimal_auc': 0.9808353808353808, 'imitation_auc': 0.6543478260869566, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7482993197278912}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6624284806102988, 'optimal_acc': 1.0, 'imitation_acc': 0.7619047619047619}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 105 _____
val reward 1.6509263515472412
imitation reward 3.161350727081299
distance losses 0.0 0.0
distributions [0.6176060438156128, 0.27834105491638184, 6.996784236434905e-07]
[{'decision': 0, 'optimal_auc': 0.714258039519566, 'imitation_auc': 0.5729961832061068, 'optimal_acc': 0.6530612244897959, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9813267813267813, 'imitation_auc': 0.6497282608695653, 'optimal_acc': 0.9387755102040817, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6547997457088366, 'optimal_acc': 1.0, 'imitation_acc': 0.7551020408163265}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 106 _____
val reward 1.664160966873169
imitation reward 3.1826553344726562
distance losses 0.0 0.0
distributions [0.6311798095703125, 0.2886205017566681, 7.873379104239575e-07]
[{'decision': 0, 'optimal_auc': 0.7098024021697017, 'imitation_auc': 0.5696564885496184, 'optimal_acc': 0.6462585034013606, 'imitation_acc': 0.8299319727891157}, {'decision': 1, 'optimal_auc': 0.985012285012285, 'imitation_auc': 0.6505434782608697, 'optimal_acc': 0.9455782312925171, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6532104259376986, 'optimal_acc': 1.0, 'imitation_acc': 0.7414965986394558}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 107 _____
val reward 1.6981865167617798
imitation reward 3.47360897064209
distance losses 0.0 0.0
distributions [0.6538870930671692, 0.30209580063819885, 8.828275781525008e-07]
[{'decision': 0, 'optimal_auc': 0.7051530414567998, 'imitation_auc': 0.5622614503816794, 'optimal_acc': 0.6394557823129252, 'imitation_acc': 0.8435374149659864}, {'decision': 1, 'optimal_auc': 0.9864864864864864, 'imitation_auc': 0.6497282608695653, 'optimal_acc': 0.9251700680272109, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.64907819453274, 'optimal_acc': 1.0, 'imitation_acc': 0.7414965986394558}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 108 _____
val reward 1.6977871656417847
imitation reward 3.4458189010620117
distance losses 0.0 0.0
distributions [0.6505816578865051, 0.3095056414604187, 1.095978859666502e-06]
[{'decision': 0, 'optimal_auc': 0.7016660209221233, 'imitation_auc': 0.5541507633587786, 'optimal_acc': 0.6394557823129252, 'imitation_acc': 0.8367346938775511}, {'decision': 1, 'optimal_auc': 0.9891891891891892, 'imitation_auc': 0.6529891304347826, 'optimal_acc': 0.9183673469387755, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6589319771137954, 'optimal_acc': 1.0, 'imitation_acc': 0.7414965986394558}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 109 _____
val reward 1.660269856452942
imitation reward 3.430338144302368
distance losses 0.0 0.0
distributions [0.6304022669792175, 0.30962663888931274, 1.3826449958287412e-06]
[{'decision': 0, 'optimal_auc': 0.7034095311894615, 'imitation_auc': 0.552719465648855, 'optimal_acc': 0.6530612244897959, 'imitation_acc': 0.8163265306122449}, {'decision': 1, 'optimal_auc': 0.9906633906633906, 'imitation_auc': 0.65625, 'optimal_acc': 0.9183673469387755, 'imitation_acc': 0.7619047619047619}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6665607120152575, 'optimal_acc': 1.0, 'imitation_acc': 0.7687074829931972}]
tensor([0.6054, 0.2517, 0.0000], grad_fn=<MeanBackward1>)
______epoch 110 _____
val reward 1.628965139389038
imitation reward 3.112860679626465
distance losses 0.0 0.0
distributions [0.601446807384491, 0.3063349723815918, 1.7157493630293175e-06]
[{'decision': 0, 'optimal_auc': 0.7084463386284386, 'imitation_auc': 0.5522423664122138, 'optimal_acc': 0.6530612244897959, 'imitation_acc': 0.8095238095238095}, {'decision': 1, 'optimal_auc': 0.9901719901719902, 'imitation_auc': 0.6627717391304349, 'optimal_acc': 0.9183673469387755, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.6710108073744437, 'optimal_acc': 1.0, 'imitation_acc': 0.7551020408163265}]
++++++++++Final+++++++++++
best tensor(1.5041, grad_fn=<AddBackward0>)
[{'decision': 0, 'optimal_auc': 0.7140643161565285, 'imitation_auc': 0.5815839694656488, 'optimal_acc': 0.6598639455782312, 'imitation_acc': 0.8775510204081632}, {'decision': 1, 'optimal_auc': 0.9972972972972973, 'imitation_auc': 0.69375, 'optimal_acc': 0.9591836734693877, 'imitation_acc': 0.7551020408163265}, {'decision': 2, 'optimal_auc': -1, 'imitation_auc': 0.8391608391608392, 'optimal_acc': 1.0, 'imitation_acc': 0.8163265306122449}]

/tmp/ipykernel_2619893/3871624404.py:355: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(save_file))

tensor(1.5041, grad_fn=<AddBackward0>)

In [35]:
pd.DataFrame(rad_results[1]).set_index('decision') - pd.DataFrame(control_results[1]).set_index('decision')

          optimal_auc  imitation_auc  optimal_acc  imitation_acc
decision
0            0.122191       0.023855     0.210884       0.000000
1           -0.015479      -0.037500    -0.006803       0.013605
2            0.000000      -0.028926     0.000000       0.006803

In [ ]:
pd.DataFrame(control_results[1])

In [38]:
rad_decision_model = rad_results[0]
rad_decision_model.set_device('cpu')
torch.save(rad_decision_model,'../resources/radcluster_decision_model.pt')
pd.DataFrame(rad_results[1]).to_csv('../results/radcluster_policy_model_score.csv')
rad_decision_model

DecisionAttentionModel(
  (input_dropout): Dropout(p=0.1, inplace=False)
  (layers): ModuleList(
    (0): Linear(in_features=100, out_features=1000, bias=True)
  )
  (batchnorm): BatchNorm1d(1000, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (dropout): Dropout(p=0.25, inplace=False)
  (relu): Softplus(beta=1.0, threshold=20.0)
  (sigmoid): Sigmoid()
  (softmax): Softmax(dim=1)
  (final_opt_layer): Linear(in_features=1000, out_features=100, bias=True)
  (final_imitation_layer): Linear(in_features=1000, out_features=100, bias=True)
  (final_layer): Linear(in_features=1000, out_features=6, bias=True)
  (resize_layer): Linear(in_features=98, out_features=100, bias=True)
  (attentions): ModuleList(
    (0): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=100, out_features=100, bias=True)
    )
  )
  (norms): ModuleList(
    (0): LayerNorm((100,), eps=1e-05, elementwise_affine=True)
  )
  (activation): ReLU()
)